// Pulls CMS-managed guides from the backend and writes the TS module the app
// imports. Same shape as scripts/generate-locations.mjs — the build stays fully
// static, and the site never talks to the CMS or the database at runtime.
import fs from 'node:fs/promises';
import path from 'node:path';
import { fetchGuides } from './lib/api.mjs';

// `published` is optional in the Guide interface, and the API omits it rather
// than sending null. Dropping undefined keys keeps the emitted literal clean
// and matches how the hand-written file looked.
const dropUndefined = (obj) =>
  Object.fromEntries(Object.entries(obj).filter(([, v]) => v !== undefined));

async function main() {
  const guides = (await fetchGuides()).map(dropUndefined);

  const body = `// AUTO-GENERATED by scripts/generate-guides.mjs — do not edit by hand.
// Regenerated on every \`npm run build\`. Source: backend /guides (CMS-managed).
// Types live in ./guides.ts, which re-exports this data.
import type { Guide } from './guides';

export const guides: Guide[] = ${JSON.stringify(guides, null, 2)};
`;

  const outPath = path.join('src', 'data', 'guides.generated.ts');
  await fs.mkdir(path.dirname(outPath), { recursive: true });
  await fs.writeFile(outPath, body, 'utf8');
  console.log(
    `[guides] wrote ${outPath} — ${guides.length} guides (${guides.reduce((n, g) => n + g.blocks.length, 0)} blocks, ${guides.reduce((n, g) => n + g.faqs.length, 0)} FAQs)`,
  );
}

main().catch((err) => {
  console.error('[guides] generation failed:', err);
  process.exit(1);
});
