// Pulls CMS-managed blogs from the backend and writes the TS module the app
// imports. Same shape as scripts/generate-locations.mjs — the build stays fully
// static, and the site never talks to the CMS or the database at runtime.
import fs from 'node:fs/promises';
import path from 'node:path';
import { fetchBlogs } from './lib/api.mjs';

// `published` is optional in the Blog interface, and the API omits it rather
// than sending null. Dropping undefined keys keeps the emitted literal clean
// and matches how the hand-written file looked.
const dropUndefined = (obj) =>
  Object.fromEntries(Object.entries(obj).filter(([, v]) => v !== undefined));

async function main() {
  const blogs = (await fetchBlogs()).map(dropUndefined);

  const body = `// AUTO-GENERATED by scripts/generate-blogs.mjs — do not edit by hand.
// Regenerated on every \`npm run build\`. Source: backend /blogs (CMS-managed).
// Types live in ./blogs.ts, which re-exports this data.
import type { Blog } from './blogs';

export const blogs: Blog[] = ${JSON.stringify(blogs, null, 2)};
`;

  const outPath = path.join('src', 'data', 'blogs.generated.ts');
  await fs.mkdir(path.dirname(outPath), { recursive: true });
  await fs.writeFile(outPath, body, 'utf8');
  console.log(
    `[blogs] wrote ${outPath} — ${blogs.length} blogs (${blogs.reduce((n, g) => n + g.blocks.length, 0)} blocks, ${blogs.reduce((n, g) => n + g.faqs.length, 0)} FAQs)`,
  );
}

main().catch((err) => {
  console.error('[blogs] generation failed:', err);
  process.exit(1);
});
