// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrotnovxfqieofaxzmyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyb3Rub3Z4ZnFpZW9mYXh6bXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzU5ODMsImV4cCI6MjA2MTY1MTk4M30.NdNb0XYdz8FCsEyS77EyTXZilXGdNX7lvt4y1TtnNoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);