// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diqgawsalwqfcisexmws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpcWdhd3NhbHdxZmNpc2V4bXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjkwNDYsImV4cCI6MjA2MTQ0NTA0Nn0.kHOAtEOI9CSPo9hF0F4vSaGqq2k91xF5ZBQbVesR7tY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);