// AUTO-GENERATED by scripts/generate-blogs.mjs — do not edit by hand.
// Indexes and related links need metadata, not complete article bodies.
import type { Blog } from './blogs';
import { normalizeContentPunctuation } from '@/lib/contentPunctuation';
export const blogSummaries: Pick<Blog, 'slug' | 'title' | 'description' | 'updated'>[] = normalizeContentPunctuation([
  {
    "slug": "peb-vs-rcc-warehouse",
    "title": "PEB vs RCC Warehouse - Which Should You Lease in India?",
    "description": "PEB (pre-engineered building) vs RCC warehouse compared: construction, clear height, cost, fire safety, and which suits 3PL, e-commerce, manufacturing or cold storage.",
    "updated": "2026-06-05"
  },
  {
    "slug": "grade-a-warehouse-india",
    "title": "What Is a Grade A Warehouse in India? Grade A vs B vs C Explained",
    "description": "What qualifies as a Grade A warehouse in India: clear height, FM2 flooring, docks, fire systems. Grade A vs Grade B vs Grade C compared, with typical rent impact.",
    "updated": "2026-06-05"
  },
  {
    "slug": "warehouse-compliance-checklist-india",
    "title": "Warehouse Compliance Checklist for India: Licences, NOCs & Lease Paperwork",
    "description": "Every licence and document needed to lease and operate a warehouse in India: fire NOC, building OC, land-use conversion, GST additional place of business, FSSAI, pollution consents, lease registration.",
    "updated": "2026-06-05"
  },
  {
    "slug": "warehouse-rent-india-guide",
    "title": "Warehouse Rent in India: What Drives the ₹/sqft and Typical Lease Terms",
    "description": "What determines warehouse rent per sqft in India: micro-market, grade, size, compliance. Typical lease terms — security deposit, lock-in, escalation, CAM — and how to negotiate.",
    "updated": "2026-07-03"
  },
  {
    "slug": "carpet-area-vs-built-up-area-warehouse",
    "title": "Carpet Area vs Built-Up Area in a Warehouse: Which One Are You Paying Rent On?",
    "description": "Carpet, built-up and super built-up area in warehouse leases: what each includes, the loading factor, why RERA's carpet-area rule doesn't apply, and how to compare quotes on effective rate per usable sqft.",
    "updated": "2026-07-03"
  },
  {
    "slug": "dabaspet-multimodal-logistics-park",
    "title": "Dabaspet Multimodal Logistics Park: What Bengaluru's Rs 1,770 Crore MMLP Means for Warehousing",
    "description": "Bangalore's 400-acre Dabaspet MMLP runs in phases to 2039. What the Rs 1,770 crore park changes for warehouse and godowns.",
    "updated": "2026-08-13"
  }
]);
