// AUTO-GENERATED by scripts/generate-blogs.mjs — do not edit by hand.
// Regenerated on every `npm run build`. Source: backend /blogs (CMS-managed).
// Types live in ./blogs.ts, which re-exports this data.
import type { Blog } from './blogs';

export const blogs: Blog[] = [
  {
    "slug": "peb-vs-rcc-warehouse",
    "title": "PEB vs RCC Warehouse: Which Should You Lease in India?",
    "seoTitle": "PEB vs RCC Warehouse — Differences, Costs & Which to Lease | WareOnGo",
    "description": "PEB (pre-engineered building) vs RCC warehouse compared: construction, clear height, cost, fire safety, and which suits 3PL, e-commerce, manufacturing or cold storage.",
    "summary": "PEB (pre-engineered building) warehouses are steel structures — faster to build, cheaper per sqft at scale, with higher clear heights and wider column-free spans, making them the default for modern Grade A logistics. RCC (reinforced cement concrete) warehouses are concrete structures — slower and costlier to build but better suited to multi-storey use, heavy point loads, and in-city locations. For most leasing decisions: large single-storey distribution → PEB; small in-city godown or multi-floor use → RCC.",
    "published": "2026-06-04",
    "updated": "2026-06-05",
    "keywords": [
      "PEB warehouse",
      "RCC warehouse",
      "PEB vs RCC",
      "pre-engineered building warehouse India",
      "warehouse construction types India",
      "Grade A warehouse construction"
    ],
    "blocks": [
      {
        "kind": "p",
        "text": "Almost every warehouse listed in India is described as either PEB or RCC. The label refers to how the structure is built, but it has practical consequences for the tenant: clear height, racking density, fire-safety design, ambient temperature, and rent. This guide explains both, compares them point by point, and tells you which to shortlist for your use case."
      },
      {
        "kind": "h2",
        "text": "What is a PEB warehouse?"
      },
      {
        "kind": "p",
        "text": "A pre-engineered building (PEB) is a steel structure whose columns, rafters and purlins are designed and fabricated off-site in a factory, then bolted together on a concrete plinth at the site. The roof and walls are metal sheeting (usually colour-coated galvalume), often with insulation and polycarbonate skylights. Because the steel frame carries the load, PEB sheds achieve wide column-free spans — typically 20–30 m between columns, and far more with trusses — and eaves heights of 9–13.5 m."
      },
      {
        "kind": "ul",
        "items": [
          "Construction time: typically 4–6 months for a standard big-box shed — roughly 2–3× faster than equivalent RCC.",
          "Clear height: commonly 9–13.5 m at eaves, enabling 4–6 racking levels (VNA racking goes higher).",
          "Spans: wide column-free grids, so racking layouts and material-handling routes are flexible.",
          "Expansion: bays can be added lengthwise later — useful for build-to-suit campuses.",
          "Almost all Grade A logistics parks in India (NH-48 Bengaluru, Bhiwandi, Chakan, Farukhnagar, Hosur) are PEB."
        ]
      },
      {
        "kind": "h2",
        "text": "What is an RCC warehouse?"
      },
      {
        "kind": "p",
        "text": "A reinforced cement concrete (RCC) warehouse uses cast-in-place concrete columns, beams and slabs. It is the construction style of most older godowns, in-city storage buildings and any multi-storey warehouse. RCC structures take longer to build and cost more per square foot of covered area for large single-storey footprints, but concrete brings real advantages: high inherent fire resistance, better thermal mass (cooler interiors without insulation), and the ability to carry upper floors."
      },
      {
        "kind": "ul",
        "items": [
          "Construction time: typically 12–18 months for a comparable footprint.",
          "Clear height: usually 4.5–8 m per floor — lower than PEB, limiting vertical racking.",
          "Multi-storey: the only practical option for G+1/G+2 warehousing in land-scarce city locations.",
          "Fire: concrete is non-combustible with high fire ratings by default; steel needs applied fire protection and sprinklers to match.",
          "Temperature: thicker thermal mass keeps interiors cooler — relevant for commodities sensitive to heat."
        ]
      },
      {
        "kind": "h2",
        "text": "PEB vs RCC: side-by-side comparison"
      },
      {
        "kind": "table",
        "table": {
          "rows": [
            [
              "Structure",
              "Factory-fabricated steel frame, metal sheeting",
              "Cast-in-place concrete frame and slabs"
            ],
            [
              "Typical clear height",
              "9–13.5 m at eaves",
              "4.5–8 m per floor"
            ],
            [
              "Column-free span",
              "Wide (20–30 m+); flexible racking",
              "Narrower grids; columns interrupt layout"
            ],
            [
              "Construction time",
              "4–6 months",
              "12–18 months"
            ],
            [
              "Shell cost at scale",
              "Lower per sqft for large single-storey boxes",
              "Higher for the same footprint"
            ],
            [
              "Multi-storey",
              "Rare (mezzanines only)",
              "Standard (G+1, G+2 common in cities)"
            ],
            [
              "Fire resistance",
              "Steel loses strength in fire; needs sprinklers/fire-rated design",
              "Inherently high fire rating"
            ],
            [
              "Heat inside",
              "Hotter unless roof is insulated",
              "Cooler due to thermal mass"
            ],
            [
              "Typical use",
              "Grade A logistics, 3PL, e-commerce fulfilment, light manufacturing",
              "In-city godowns, cold storage shells, multi-floor storage, heavy industry"
            ],
            [
              "Where you find them",
              "Highway logistics corridors and industrial parks",
              "City peripheries, older industrial areas, urban godown clusters"
            ]
          ],
          "headers": [
            "Factor",
            "PEB warehouse",
            "RCC warehouse"
          ]
        }
      },
      {
        "kind": "h2",
        "text": "Which should you lease?"
      },
      {
        "kind": "h3",
        "text": "Choose PEB if…"
      },
      {
        "kind": "ul",
        "items": [
          "You need 20,000+ sqft of single-storey space for distribution, fulfilment or 3PL operations.",
          "You rack vertically — pallet racking beyond 3 levels effectively requires 9 m+ clear height.",
          "Dock operations matter: modern PEB parks come with dock levellers, large truck courts and container access.",
          "You want Grade A compliance (sprinklers, FM-grade flooring, insurance-friendly construction) — the Grade A supply in India is overwhelmingly PEB."
        ]
      },
      {
        "kind": "h3",
        "text": "Choose RCC if…"
      },
      {
        "kind": "ul",
        "items": [
          "You need a small (2,000–15,000 sqft) godown inside city limits for last-mile or dark-store operations — in-city stock is mostly RCC.",
          "Your goods are heat-sensitive and the budget does not stretch to an insulated PEB.",
          "You need upper floors, or heavy point loads such as machine foundations.",
          "The micro-market you must be in simply has no PEB supply — many older industrial areas are entirely RCC."
        ]
      },
      {
        "kind": "p",
        "text": "In practice the decision is usually made by the micro-market: highway logistics corridors offer PEB, urban godown clusters offer RCC, and the right answer is the building that puts you closest to your demand at a workable rent. Listing pages on WareOnGo are segmented by construction type per city, so you can compare actual PEB and RCC availability side by side before deciding."
      },
      {
        "kind": "h2",
        "text": "Lifecycle and cost comparison"
      },
      {
        "kind": "p",
        "text": "Tenants rarely pay construction costs directly, but the economics of the building flow through to rent, maintenance recoveries and exit flexibility. The broad lifecycle picture:"
      },
      {
        "kind": "table",
        "table": {
          "rows": [
            [
              "Shell construction cost",
              "Lower per sqft for large single-storey boxes",
              "Higher for the same covered area"
            ],
            [
              "Construction time",
              "4–6 months",
              "12–18 months"
            ],
            [
              "Design lifespan",
              "~30–50 years with maintained coatings",
              "~50+ years"
            ],
            [
              "Maintenance pattern",
              "Periodic repainting/sheeting care; bolt-torque checks",
              "Lower routine upkeep; concrete repairs are lumpier"
            ],
            [
              "Modification & expansion",
              "Bays added lengthwise; openings cut easily",
              "Structural changes are slow and costly"
            ],
            [
              "Insurance view",
              "Accepted with sprinklers/fire design in place",
              "Favourable due to inherent fire rating"
            ],
            [
              "Resale/re-let flexibility",
              "High in logistics corridors",
              "High in urban locations"
            ]
          ],
          "headers": [
            "Lifecycle factor",
            "PEB",
            "RCC"
          ]
        }
      },
      {
        "kind": "h2",
        "text": "Which construction suits which industry?"
      },
      {
        "kind": "table",
        "table": {
          "rows": [
            [
              "3PL / multi-client logistics",
              "PEB",
              "High cube, flexible racking layouts, dock-led operations"
            ],
            [
              "E-commerce fulfilment",
              "PEB",
              "Mezzanine-friendly spans, 10 m+ clear heights for pick towers"
            ],
            [
              "Dark stores / quick commerce",
              "RCC",
              "In-city locations dominate; small footprints; proximity beats spec"
            ],
            [
              "Food & FMCG storage",
              "Either",
              "Insulated PEB for ambient control, or RCC for thermal mass — FSSAI compliance matters more than frame"
            ],
            [
              "Pharma & cold chain",
              "RCC shell or insulated PEB",
              "Temperature stability and validated envelopes drive the choice"
            ],
            [
              "Light manufacturing",
              "PEB",
              "Wide spans for lines, easy utility routing, faster possession"
            ],
            [
              "Heavy machinery / point loads",
              "RCC",
              "Floor and frame tolerate concentrated structural loads"
            ]
          ],
          "headers": [
            "Use case",
            "Usual pick",
            "Why"
          ]
        }
      }
    ],
    "faqs": [
      {
        "a": "PEB stands for pre-engineered building — a steel structure whose frame is fabricated in a factory and bolted together on site. Most modern Grade A warehouses in India are PEB.",
        "q": "What does PEB stand for in warehousing?"
      },
      {
        "a": "For large single-storey warehouses, yes — a PEB shell is typically cheaper per sqft and 2–3× faster to build than equivalent RCC. For small buildings or multi-storey structures the gap narrows or reverses.",
        "q": "Is PEB cheaper than RCC?"
      },
      {
        "a": "Concrete is non-combustible and holds strength in fire far longer than unprotected steel, so RCC has an inherent advantage. A sprinklered, fire-NOC-compliant PEB is considered safe for insurance and regulatory purposes — what matters is the fire systems, not just the frame material.",
        "q": "Is an RCC warehouse safer in a fire?"
      },
      {
        "a": "As a rule of thumb, each pallet racking level needs roughly 1.8–2 m. A 6 m RCC godown fits about 3 levels; a 12 m PEB fits 5–6. If your storage plan is vertical, the PEB premium usually pays for itself in cube utilisation.",
        "q": "What clear height do I need for pallet racking?"
      },
      {
        "a": "Yes — expandability is one of PEB's structural advantages. Bays can be added lengthwise and wall openings cut with relative ease, which is why build-to-suit campuses are almost always PEB. RCC structures can be extended too, but modifications are slower, costlier and structurally more invasive.",
        "q": "Can a PEB warehouse be expanded later?"
      },
      {
        "a": "A well-maintained PEB structure is typically designed for 30–50 years, with lifespan hinging on coating and sheeting upkeep. RCC structures generally last 50+ years with less routine maintenance. For a tenant on a 3–9 year lease, building age and maintenance condition matter more than the theoretical lifespan.",
        "q": "How long does a PEB warehouse last compared to RCC?"
      }
    ],
    "related": [
      "grade-a-warehouse-india",
      "warehouse-rent-india-guide"
    ]
  },
  {
    "slug": "grade-a-warehouse-india",
    "title": "What Is a Grade A Warehouse in India? Grade A vs B vs C Explained",
    "seoTitle": "Grade A Warehouse Meaning in India — Grade A vs B vs C | WareOnGo",
    "description": "What qualifies as a Grade A warehouse in India: clear height, FM2 flooring, docks, fire systems. Grade A vs Grade B vs Grade C compared, with typical rent impact.",
    "summary": "A Grade A warehouse in India is a modern, institutionally built facility with roughly 10–12 m clear height, FM2-grade flat flooring rated around 5–7 tonnes/sqm, dock levellers (about one per 10,000 sqft), sprinkler and hydrant fire systems, a 30 m+ truck court, insulated roofing with skylights, and full statutory compliance. Grade B is functional but misses several of these specs; Grade C is basic godown stock. Grade A commands a rent premium of roughly 20–40% over Grade B in the same micro-market, which efficient cube utilisation and lower operating risk often offset.",
    "published": "2026-06-04",
    "updated": "2026-06-05",
    "keywords": [
      "Grade A warehouse India",
      "Grade A warehouse meaning",
      "Grade A vs Grade B warehouse",
      "warehouse grading India",
      "FM2 flooring warehouse",
      "Grade A warehouse specifications"
    ],
    "blocks": [
      {
        "kind": "p",
        "text": "There is no statutory definition of \"Grade A\" in India — the grading is a market convention used by industrial real-estate consultants, developers and occupiers. But the convention is consistent enough that the label carries real meaning in lease negotiations, insurance underwriting and operations planning. This guide lays out the accepted specification, contrasts grades A, B and C, and explains when paying the Grade A premium is rational."
      },
      {
        "kind": "h2",
        "text": "The Grade A specification"
      },
      {
        "kind": "ul",
        "items": [
          "Clear height: 10–12 m at eaves (some new parks go higher), enabling 5–6 racking levels.",
          "Flooring: FM2-category flatness, trimix/VDF concrete, load rating around 5–7 tonnes/sqm — required for VNA forklifts and high racking.",
          "Docks: dock levellers at roughly 1 per 10,000 sqft, dock height ~1.2 m, sectional doors, dock shelters in newer parks.",
          "Fire: sprinklers throughout (ESFR in newer builds), hydrant ring main, fire NOC in place, adequate water storage.",
          "Truck court: 30 m+ apron depth so 40-ft containers can dock and turn without blocking circulation.",
          "Structure: PEB with insulated roof, ~3–5% skylights for daylight, ventilation (ridge vents/louvres).",
          "Power & utilities: sanctioned power adequate for MHE charging and lighting, DG backup provision, borewell/water connection.",
          "Compliance & title: clean land title, approved building plan, occupancy certificate, CLU/industrial land use — institutionally developed parks come pre-papered.",
          "Site: gated campus, 24×7 security, weighbridge in larger parks, driver amenities, increasingly solar rooftops and ESG certifications."
        ]
      },
      {
        "kind": "h2",
        "text": "Grade A vs Grade B vs Grade C"
      },
      {
        "kind": "table",
        "table": {
          "rows": [
            [
              "Clear height",
              "10–12 m+",
              "6–9 m",
              "Under 6 m"
            ],
            [
              "Flooring",
              "FM2 flat, 5–7 t/sqm",
              "Plain VDF/trimix, uneven possible",
              "Basic PCC, undulating"
            ],
            [
              "Docks",
              "Levellers ~1/10,000 sqft",
              "Raised platform, few or no levellers",
              "Ground-level loading only"
            ],
            [
              "Fire systems",
              "Sprinklers + hydrants + NOC",
              "Extinguishers/hydrants, NOC varies",
              "Often non-compliant"
            ],
            [
              "Construction",
              "New PEB, insulated",
              "Older PEB or good RCC",
              "Old RCC/sheds"
            ],
            [
              "Compliance paperwork",
              "Complete, institutional",
              "Mostly available",
              "Frequently incomplete"
            ],
            [
              "Typical occupiers",
              "E-commerce, 3PL, FMCG, auto",
              "Regional distribution, SMEs",
              "Local traders, overflow storage"
            ],
            [
              "Indicative rent vs Grade B",
              "+20–40%",
              "Baseline",
              "−20–40%"
            ]
          ],
          "headers": [
            "Attribute",
            "Grade A",
            "Grade B",
            "Grade C"
          ]
        }
      },
      {
        "kind": "h2",
        "text": "Is the Grade A premium worth it?"
      },
      {
        "kind": "p",
        "text": "Run the comparison on cost per pallet position, not cost per square foot. A 12 m Grade A box racked 5-high can hold roughly twice the pallets of a 6 m Grade B shed of the same footprint — so even at a 30% rent premium, the Grade A facility is often cheaper per unit stored. Add the harder-to-quantify items: lower fire-insurance friction, fewer compliance surprises at licence time, faster truck turnaround at proper docks, and MHE that works on flat floors."
      },
      {
        "kind": "p",
        "text": "Grade A stops making sense when the operation cannot use the cube: ground-stacked goods, slow-moving inventory, very small footprints, or pure last-mile nodes where proximity beats specification. For dark stores and city fulfilment, a compliant Grade B RCC godown at the right pin code routinely beats a Grade A box 40 km away."
      },
      {
        "kind": "h2",
        "text": "How to verify a \"Grade A\" claim"
      },
      {
        "kind": "ol",
        "items": [
          "Measure clear height at the lowest obstruction (sprinkler pipes, ducts), not at the ridge.",
          "Ask for the floor specification — flatness category and load rating in t/sqm — in writing.",
          "Count the dock levellers and check apron depth against a 40-ft container turning circle.",
          "Inspect the fire NOC, sprinkler coverage and the water tank capacity, not just the hardware.",
          "Check the paperwork: building approval, occupancy certificate, land-use conversion. A great shed on unconverted land is not Grade A in any way that protects you."
        ]
      },
      {
        "kind": "p",
        "text": "Every listing on WareOnGo is physically inspected and its specifications and compliances validated before it goes live, so grade claims are verified rather than self-declared."
      },
      {
        "kind": "h2",
        "text": "Where Grade A supply is concentrated in India"
      },
      {
        "kind": "p",
        "text": "Grade A development clusters along highway corridors at the edges of major consumption markets. If your requirement is Grade A, these are the micro-markets where supply actually exists:"
      },
      {
        "kind": "table",
        "table": {
          "rows": [
            [
              "Delhi NCR",
              "Farukhnagar, Pataudi Road, Bilaspur Chowk (Gurugram); Kundli–Sonipat; Dadri & Greater Noida"
            ],
            [
              "Mumbai MMR",
              "Bhiwandi, Panvel, Taloja, JNPT influence zone"
            ],
            [
              "Bengaluru",
              "Nelamangala, Dabaspete, Hoskote, Bommasandra, Attibele"
            ],
            [
              "Chennai",
              "Oragadam, Sriperumbudur, Gummidipoondi, Red Hills"
            ],
            [
              "Pune",
              "Chakan, Ranjangaon, Talegaon"
            ],
            [
              "Hyderabad",
              "Medchal, Patancheru, Shamshabad, Shadnagar"
            ],
            [
              "Kolkata",
              "Dankuni, Dhulagarh, NH-16/NH-19 corridors"
            ],
            [
              "Ahmedabad",
              "Aslali, Changodar, Sanand, Bavla"
            ]
          ],
          "headers": [
            "Market",
            "Key Grade A corridors"
          ]
        }
      },
      {
        "kind": "h2",
        "text": "Site-visit checklist: question by question"
      },
      {
        "kind": "table",
        "table": {
          "rows": [
            [
              "Clear height",
              "Measure to the lowest obstruction (sprinkler runs, ducts)",
              "Height quoted at the ridge, not the obstruction"
            ],
            [
              "Flooring",
              "Flatness category and load rating in writing",
              "\"Heavy duty\" with no number behind it"
            ],
            [
              "Docks",
              "Leveller count vs your truck mix; apron depth for 40-ft containers",
              "Raised platform only, levellers \"planned\""
            ],
            [
              "Fire systems",
              "Sprinkler coverage map, water tank capacity, NOC validity date",
              "Hardware present but NOC expired or pending"
            ],
            [
              "Power",
              "Sanctioned load on the bill, not the transformer rating",
              "Sanction application \"in process\""
            ],
            [
              "Paperwork",
              "Building approval, occupancy certificate, land-use conversion",
              "Any one of the three missing"
            ]
          ],
          "headers": [
            "Spec",
            "What to ask / measure",
            "Red flag"
          ]
        }
      }
    ],
    "faqs": [
      {
        "a": "Market convention in India puts Grade A clear height at roughly 10–12 m at the eaves. Anything below about 9 m is generally marketed as Grade B regardless of other specifications.",
        "q": "What is the minimum clear height for a Grade A warehouse?"
      },
      {
        "a": "No. Warehouse grading is a market convention, not a statutory standard — which is why specifications should be verified line by line during diligence rather than taken from the brochure.",
        "q": "Is there an official Grade A certification in India?"
      },
      {
        "a": "Typically a 20–40% rent premium over Grade B in the same micro-market. Measured per pallet position rather than per sqft, Grade A often comes out cheaper because of vertical storage.",
        "q": "How much more expensive is Grade A?"
      },
      {
        "a": "FM2 is a floor-flatness category (from the UK TR34 standard, widely referenced in India) indicating a high-tolerance flat floor. It matters because high racking and VNA forklifts need flat, jointed concrete to operate safely at height.",
        "q": "What is FM2 flooring?"
      },
      {
        "a": "Often yes, via shared occupancy: most Grade A parks lease compartments from roughly 20,000 sqft, and 3PLs sub-offer even smaller dedicated areas inside Grade A boxes. SMEs get institutional infrastructure and compliance without leasing an entire building.",
        "q": "Is Grade A worth it for small and mid-size businesses?"
      },
      {
        "a": "Along highway corridors at the edge of major markets — Bhiwandi and Panvel around Mumbai, Farukhnagar and Kundli in NCR, Nelamangala and Hoskote around Bengaluru, Oragadam and Sriperumbudur near Chennai, Chakan near Pune, and Medchal and Shamshabad around Hyderabad.",
        "q": "Where do I find Grade A warehouses in India?"
      }
    ],
    "related": [
      "peb-vs-rcc-warehouse",
      "warehouse-rent-india-guide"
    ]
  },
  {
    "slug": "warehouse-compliance-checklist-india",
    "title": "Warehouse Compliance Checklist for India: Licences, NOCs & Lease Paperwork",
    "seoTitle": "Warehouse Compliance Checklist India — Fire NOC, GST, Licences | WareOnGo",
    "description": "Every licence and document needed to lease and operate a warehouse in India: fire NOC, building OC, land-use conversion, GST additional place of business, FSSAI, pollution consents, lease registration.",
    "summary": "To lease and operate a warehouse in India you need to verify the landlord's papers (clean title, approved building plan, occupancy certificate, industrial/warehouse land-use, fire NOC) and then obtain your own registrations: GST additional place of business, trade licence, shops & establishments registration, plus sector-specific licences such as FSSAI for food, drug licence for pharma, or pollution-board consents for chemicals. Leases longer than 11 months must be stamped and registered. Missing any one of these can stall operations, invalidate insurance, or block input-tax credit.",
    "published": "2026-06-04",
    "updated": "2026-06-05",
    "keywords": [
      "warehouse compliance checklist India",
      "fire NOC warehouse",
      "GST additional place of business warehouse",
      "warehouse licence India",
      "FSSAI warehouse storage licence",
      "warehouse lease registration India"
    ],
    "blocks": [
      {
        "kind": "p",
        "text": "Compliance is where Indian warehouse deals slip their timelines. The shed may be ready, but if the fire NOC is pending or the land was never converted from agricultural use, you cannot legally stock goods — and your insurer may decline a claim even if you do. This checklist covers the three layers: documents the landlord must hold, registrations the tenant must obtain, and the lease formalities that make the contract enforceable."
      },
      {
        "kind": "h2",
        "text": "Layer 1 — Verify the landlord's documents before signing"
      },
      {
        "kind": "ul",
        "items": [
          "Title documents and encumbrance certificate — confirm the lessor actually owns (or has rights to lease) the property, with no undisclosed mortgage that could disrupt your tenancy.",
          "Land-use status — the land must be converted/zoned for industrial or warehousing use (CLU/NA conversion depending on the state). Warehouses on unconverted agricultural land are a common and serious red flag.",
          "Sanctioned building plan and occupancy/completion certificate — the structure you are leasing should match the approved plan.",
          "Fire NOC from the state fire department — required for warehouses above state-specific thresholds of height and area; verify it covers the actual building and is current, as NOCs require periodic renewal.",
          "Property tax receipts and electricity/water connections in order — arrears surface later as disconnection threats.",
          "Structural stability certificate where the building is older — some municipal licences ask for it."
        ]
      },
      {
        "kind": "h2",
        "text": "Layer 2 — Registrations the tenant needs to operate"
      },
      {
        "kind": "ul",
        "items": [
          "GST — add the warehouse as an \"additional place of business\" on your GST registration in that state (a new GSTIN if you have no prior registration in the state). Without it, stocking goods there is non-compliant and e-way bill movements to the site will not reconcile.",
          "Trade licence from the local municipal body, where applicable to storage/commercial activity.",
          "Shops & Establishments Act registration for the premises if staff are employed there (state-specific).",
          "Labour-law registrations as headcount grows: EPF, ESI, and the Contract Labour (Regulation & Abolition) Act if you deploy contract workers above the threshold.",
          "Legal metrology registration if you repack or declare weights/measures at the facility."
        ]
      },
      {
        "kind": "h3",
        "text": "Sector-specific licences"
      },
      {
        "kind": "table",
        "table": {
          "rows": [
            [
              "Food, beverages, nutraceuticals",
              "FSSAI licence for the storage premises (state or central licence depending on turnover)"
            ],
            [
              "Pharmaceuticals",
              "Drug licence (wholesale/storage) from the state drug control authority; temperature mapping for cold chain"
            ],
            [
              "Chemicals, batteries, anything with effluents or hazardous classification",
              "State Pollution Control Board consent to establish/operate; PESO licence for petroleum/explosives classes"
            ],
            [
              "Insecticides/pesticides",
              "Licence under the Insecticides Act from the state agriculture department"
            ],
            [
              "Imported goods under bond",
              "Customs bonded warehouse licence under the Customs Act"
            ],
            [
              "Agri commodities for negotiable receipts",
              "WDRA registration of the warehouse"
            ]
          ],
          "headers": [
            "If you store…",
            "You need…"
          ]
        }
      },
      {
        "kind": "h2",
        "text": "Layer 3 — Lease formalities"
      },
      {
        "kind": "ul",
        "items": [
          "Stamp duty — payable on the lease deed at state-specific rates; an under-stamped deed is inadmissible as evidence until rectified with penalty.",
          "Registration — under the Registration Act, 1908, a lease of immovable property for more than 11 months must be registered with the sub-registrar. Long-term warehouse leases (3–9 years) should always be registered; unregistered long leases are read down to month-to-month tenancies in disputes.",
          "Standard commercial terms to negotiate consciously: security deposit (commonly 3–6 months), lock-in period (often 3 years on Grade A), rent escalation (typically ~5% annually or 15% every 3 years), maintenance/CAM charges and who bears property tax and structural repairs.",
          "Fit-out and reinstatement clauses — who owns racking, dock equipment and electrical augmentation at exit.",
          "Insurance split — landlord typically insures the structure; tenant insures stock, fit-outs and liability. Verify the fire systems meet your insurer's warranties, not just the fire NOC."
        ]
      },
      {
        "kind": "h2",
        "text": "A realistic sequencing plan"
      },
      {
        "kind": "ol",
        "items": [
          "Diligence the landlord's papers (1–2 weeks; run title and land-use checks in parallel with commercial negotiation).",
          "Sign, stamp and register the lease; take possession.",
          "File the GST additional-place-of-business amendment immediately — approval is usually quick, and stocking before approval creates e-way bill friction.",
          "Apply for sector licences (FSSAI, drug, SPCB) as soon as the registered lease exists — most applications require the lease deed and premises proof.",
          "Schedule fire NOC renewal and licence renewals into your compliance calendar; lapses void insurance positions."
        ]
      },
      {
        "kind": "h2",
        "text": "Indicative licence timelines and issuing authorities"
      },
      {
        "kind": "p",
        "text": "Timelines vary by state and by how complete the application is — treat these as planning ranges, not commitments:"
      },
      {
        "kind": "table",
        "table": {
          "rows": [
            [
              "GST additional place of business",
              "GST portal (state jurisdiction)",
              "1–2 weeks"
            ],
            [
              "Fire NOC (new)",
              "State fire department",
              "4–12 weeks"
            ],
            [
              "FSSAI licence (storage)",
              "FSSAI (state/central by turnover)",
              "4–8 weeks"
            ],
            [
              "Trade licence",
              "Municipal corporation",
              "2–6 weeks"
            ],
            [
              "Shops & establishments registration",
              "State labour department",
              "1–3 weeks"
            ],
            [
              "SPCB consent to operate",
              "State pollution control board",
              "4–16 weeks"
            ],
            [
              "Drug licence (wholesale/storage)",
              "State drug control authority",
              "6–12 weeks"
            ],
            [
              "Lease registration",
              "Sub-registrar office",
              "Same day to 1 week after stamping"
            ]
          ],
          "headers": [
            "Registration / licence",
            "Issuing authority",
            "Indicative timeline"
          ]
        }
      },
      {
        "kind": "h2",
        "text": "Common compliance mistakes"
      },
      {
        "kind": "ul",
        "items": [
          "Signing before verifying land-use conversion — the single most common deal-breaker, and it invalidates everything downstream.",
          "Stocking goods before the GST additional-place-of-business amendment is approved, creating e-way bill mismatches that surface at audit.",
          "Treating an expired fire NOC as a formality — insurers treat it as a coverage gap, not paperwork.",
          "Leaving the lease unregistered to save stamp duty — in a dispute, a multi-year lease gets read down to month-to-month.",
          "Assuming the landlord's compliances cover tenant operations — they don't; the two layers are separate.",
          "Forgetting renewal calendars — fire NOCs, FSSAI and SPCB consents all lapse, and lapses are usually discovered during claims or inspections."
        ]
      },
      {
        "kind": "p",
        "text": "WareOnGo validates compliance documentation on every listed warehouse during physical verification and coordinates the diligence-to-possession paperwork end-to-end, which is how most transactions on the platform close within a couple of weeks."
      }
    ],
    "faqs": [
      {
        "a": "For warehouses above state-specific height/area thresholds, yes — the fire NOC from the state fire department is mandatory, and it requires periodic renewal. Operating without one risks sealing, prosecution and rejected insurance claims.",
        "q": "Is a fire NOC mandatory for a warehouse in India?"
      },
      {
        "a": "If you have no existing GST registration in that state, yes — you need a GSTIN there. If you already have one, you add the warehouse as an additional place of business. Either way, the warehouse must appear on your GST registration before you stock goods.",
        "q": "Do I need a separate GST registration for a warehouse in another state?"
      },
      {
        "a": "Any lease of immovable property exceeding 11 months must be registered under the Registration Act, 1908, after paying state stamp duty. Unregistered long leases are treated as month-to-month tenancies in court — a serious risk on a multi-year warehouse commitment.",
        "q": "Does a warehouse lease need to be registered?"
      },
      {
        "a": "Land-use conversion. A surprising share of otherwise good sheds sit on land never converted from agricultural use, which jeopardises every downstream licence. Verify CLU/NA status before investing time in negotiation.",
        "q": "What is the most common compliance deal-breaker?"
      },
      {
        "a": "Both, for different layers. The landlord must hold title, building approvals, land-use conversion and the fire NOC; the tenant must obtain GST, trade and sector-specific licences for their operations. A well-drafted lease records each side's obligations explicitly.",
        "q": "Who is responsible for compliance — landlord or tenant?"
      },
      {
        "a": "Typically 4–12 weeks for a new NOC from the state fire department, depending on the state, the building's readiness and inspection scheduling. Renewals are faster. Leasing a warehouse that already holds a current fire NOC removes this from your critical path entirely.",
        "q": "How long does it take to get a fire NOC for a warehouse?"
      },
      {
        "a": "Legally risky and usually a false economy. The GST amendment must precede stocking; storing food before FSSAI or regulated goods before SPCB consent exposes you to penalties and seizure. The practical play is sequencing — file everything the day the registered lease exists, and use the fit-out window as licence lead time.",
        "q": "Can I start operations while licences are pending?"
      }
    ],
    "related": [
      "warehouse-rent-india-guide",
      "grade-a-warehouse-india"
    ]
  },
  {
    "slug": "warehouse-rent-india-guide",
    "title": "Warehouse Rent in India: What Drives the ₹/sqft and Typical Lease Terms",
    "seoTitle": "Warehouse Rent in India — Rates per Sqft & Lease Terms Explained | WareOnGo",
    "description": "What determines warehouse rent per sqft in India: micro-market, grade, size, compliance. Typical lease terms — security deposit, lock-in, escalation, CAM — and how to negotiate.",
    "summary": "Warehouse rent in India is quoted in rupees per square foot per month. Three things drive it most: the micro-market, the building grade, and the deal size. Supply-heavy corridors like Bhiwandi sit at the value end. Tight urban-adjacent markets like Bengaluru sit at the premium end. On top of rent, budget for a 3-6 month security deposit, CAM charges, and roughly 5% annual escalation. Lock-ins of around 3 years are standard on Grade A leases. Rates vary sharply within one city - compare at the micro-market level, never the city average.",
    "published": "2026-06-04",
    "updated": "2026-07-03",
    "keywords": [
      "warehouse rent India",
      "warehouse rent per sqft",
      "warehouse lease terms India",
      "warehouse security deposit lock-in",
      "CAM charges warehouse",
      "Grade A warehouse rent India"
    ],
    "blocks": [
      {
        "kind": "p",
        "text": "Two warehouses 25 km apart in the same city can differ by 60% on rent. Understanding why - and what the quoted ₹/sqft does and doesn't include - is most of the work of negotiating a good warehouse lease. This guide breaks down what drives the price, the terms around the headline rate, and the levers that actually move the number."
      },
      {
        "kind": "h2",
        "text": "What determines the rate per sqft"
      },
      {
        "kind": "ul",
        "items": [
          "Micro-market, not city. What matters is proximity to highways, ring roads, the consumption centre and labour supply. A pin code with container access and city access in under an hour prices at a premium.",
          "Grade and specification. Clear height, flooring, docks, fire systems. Grade A typically rents 20-40% above Grade B in the same corridor (see our Grade A guide).",
          "Size and divisibility. Very large boxes (1 lakh+ sqft) get volume pricing. Small carve-outs of 5,000-10,000 sqft inside a larger shed cost more per sqft.",
          "Compliance completeness. A fully papered warehouse - fire NOC, occupancy certificate, converted land - commands more. It's also worth more, because the alternative shifts the risk onto you.",
          "Supply pipeline. Corridors with heavy new Grade A construction see soft rents. Land-locked urban godown clusters see steady increases.",
          "Lease tenure and tenant strength. A 9-year lease from a strong corporate tenant gets a better rate than a 2-year lease from an unknown one."
        ]
      },
      {
        "kind": "h2",
        "text": "How rent is quoted - read the fine print"
      },
      {
        "kind": "ul",
        "items": [
          "Carpet vs built-up. Confirm whether the ₹/sqft applies to carpet (usable) area or built-up area including common spaces. The same quote can differ 10–15% in real cost.",
          "CAM (common area maintenance). In organised parks this is charged separately, often a few rupees per sqft. Ask for it in writing alongside the rent.",
          "Property tax and structural repairs. Conventionally the landlord's - but verify. Some leases pass them through to you.",
          "GST on rent. Commercial rent attracts GST (currently 18%). Registered businesses can generally claim it back as input credit, but it still affects cash flow.",
          "Power, DG and water. Sanctioned load, diesel generator charges and water sit outside the rent. They matter if you run heavy equipment or cold-chain operations."
        ]
      },
      {
        "kind": "h2",
        "text": "Standard commercial terms in Indian warehouse leases"
      },
      {
        "kind": "table",
        "table": {
          "rows": [
            [
              "Security deposit",
              "3–6 months' rent",
              "Refundable, interest-free; strong tenants can negotiate it down"
            ],
            [
              "Lock-in",
              "~3 years (Grade A); 1–2 years (Grade B/C)",
              "Exiting during lock-in usually means paying the remaining lock-in rent"
            ],
            [
              "Tenure",
              "3–9 years, often 3+3+3",
              "Leases over 11 months must be stamped and registered"
            ],
            [
              "Escalation",
              "~5% per year, or 15% every 3 years",
              "It compounds — model the total cost over the full term"
            ],
            [
              "Rent-free fit-out period",
              "15–60 days",
              "Tied to fit-out scope; ask for it explicitly"
            ],
            [
              "Notice period",
              "3–6 months after lock-in",
              "Push for the same notice period on both sides"
            ]
          ],
          "headers": [
            "Term",
            "Typical range",
            "Notes"
          ]
        }
      },
      {
        "kind": "h2",
        "text": "Negotiation levers that actually work"
      },
      {
        "kind": "ol",
        "items": [
          "Cultivate Competition: Having 3-5 comparable options in the same micro-market is your single biggest source of leverage. Landlords price against the visible alternative.",
          "If you can, increase tenure to reduce the rent: A longer lock-in or tenure is worth a lower starting rent, or a longer rent-free period, to most landlords.",
          "Lease during the right time: In corridors where new parks are leasing up, developers discount to land their first tenants.",
          "Negotiate escalation and deposit, not just rent: Over a 9-year term, 1% off the annual escalation can be worth more than ₹1 off the headline rate.",
          "Look at under-construction inventory: Committing before completion routinely prices below ready stock. This is how deals close under the market rate."
        ]
      },
      {
        "kind": "h2",
        "text": "How major markets compare on Grade A rent"
      },
      {
        "kind": "p",
        "text": "The spread within a city routinely exceeds the spread between cities. Grade B stock typically sits 20–40% below Grade A in the same corridor. For current asking rates, check live listings in the specific micro-market:"
      },
      {
        "kind": "table",
        "table": {
          "rows": [
            [
              "Bengaluru (Nelamangala, Hoskote, Attibele)",
              "Premium end of the major markets — tight urban-adjacent supply"
            ],
            [
              "Delhi NCR (Farukhnagar, Kundli, Dadri)",
              "Upper band, with a wide spread between corridors"
            ],
            [
              "Pune (Chakan, Ranjangaon)",
              "Upper-mid band, supported by auto and manufacturing demand"
            ],
            [
              "Chennai (Oragadam, Sriperumbudur)",
              "Mid band — steady industrial supply keeps rates competitive"
            ],
            [
              "Hyderabad (Medchal, Shamshabad)",
              "Mid band with a healthy new-supply pipeline"
            ],
            [
              "Mumbai MMR (Bhiwandi, Panvel)",
              "Widest range — Bhiwandi anchors the value end, Panvel prices higher"
            ],
            [
              "Kolkata (Dankuni, Dhulagarh)",
              "Value end among the metros"
            ],
            [
              "Ahmedabad (Aslali, Sanand, Bavla)",
              "Value end — abundant land keeps rents soft"
            ]
          ],
          "headers": [
            "Market",
            "Relative Grade A rent positioning"
          ]
        }
      },
      {
        "kind": "h2",
        "text": "Total cost of occupancy - beyond the headline rent"
      },
      {
        "kind": "p",
        "text": "Compare options on the total cost over the full lease term, not the quoted rate. The components that move the number:"
      },
      {
        "kind": "table",
        "table": {
          "rows": [
            [
              "Base rent",
              "₹/sqft/month on built-up area",
              "Carpet vs built-up basis (~10–15% swing)"
            ],
            [
              "Escalation",
              "~5%/yr or 15% every 3 years",
              "Compounding over a 9-year term"
            ],
            [
              "CAM",
              "A few ₹/sqft in organised parks",
              "Scope creep - get the inclusion list in writing"
            ],
            [
              "Security deposit",
              "3–6 months, interest-free",
              "The cost of capital locked up"
            ],
            [
              "GST on rent",
              "18%, input credit usually available",
              "Cash-flow timing even when creditable"
            ],
            [
              "Power & DG",
              "Per-unit charges outside rent",
              "Whether the sanctioned load covers your equipment"
            ],
            [
              "Fit-out & reinstatement",
              "One-time; spread it over the lock-in",
              "Exit clauses on racking and electrical works"
            ]
          ],
          "headers": [
            "Component",
            "Typical shape",
            "Watch for"
          ]
        }
      },
      {
        "kind": "p",
        "text": "Clients transacting through WareOnGo typically save around 8-12% on commercials. Most of that comes from micro-market comparables and negotiating the full term sheet, not just the headline rent. For live availability and asking rates in a specific city, the per-city listing pages carry verified, inspected inventory with transparent pricing."
      }
    ],
    "faqs": [
      {
        "a": "In rupees per square foot per month (₹/sqft/month), usually on built-up area. Always confirm whether the quote is carpet or built-up, and what CAM, property tax and GST add on top.",
        "q": "How is warehouse rent quoted in India?"
      },
      {
        "a": "Three to six months' rent, refundable and interest-free, is the Indian market norm. Strong corporate tenants can negotiate toward the lower end.",
        "q": "What is a typical security deposit for a warehouse lease?"
      },
      {
        "a": "The initial stretch of the lease during which you cannot exit without paying the remaining lock-in rent. Around 3 years is standard on Grade A leases. Shorter lock-ins are common on smaller Grade B/C godowns.",
        "q": "What is a lock-in period?"
      },
      {
        "a": "Because warehousing prices at the micro-market level. Highway access, distance to the consumption centre, land economics and local supply vary block by block. City-average rents are nearly useless for decisions - compare specific corridors.",
        "q": "Why do rents differ so much within one city?"
      },
      {
        "a": "Yes. Commercial property rent attracts GST at the prevailing rate (18%). GST-registered tenants can generally claim input tax credit, subject to their output profile.",
        "q": "Is GST charged on warehouse rent?"
      },
      {
        "a": "Common Area Maintenance - the charge for shared infrastructure in organised parks: security, roads, drainage, landscaping, fire-system upkeep and common lighting. Typically a few rupees per sqft per month, billed alongside rent. Get the scope itemised in writing; CAM definitions vary widely between parks.",
        "q": "What are CAM charges in a warehouse lease?"
      },
      {
        "a": "Usually, yes. Asking rates carry headroom. The levers: comparables in the same micro-market, tenure and lock-in trade-offs, escalation structure, rent-free fit-out periods, and under-construction inventory. Negotiating the full term sheet rather than the headline number is how WareOnGo clients typically save 8-12% on commercials.",
        "q": "Can warehouse rent be negotiated below the quoted rate?"
      }
    ],
    "related": [
      "grade-a-warehouse-india",
      "warehouse-compliance-checklist-india",
      "carpet-area-vs-built-up-area-warehouse"
    ]
  },
  {
    "slug": "carpet-area-vs-built-up-area-warehouse",
    "title": "Carpet Area vs Built-Up Area in a Warehouse: Which One Are You Paying Rent On?",
    "seoTitle": "Carpet Area vs Built-Up Area in a Warehouse - Which One You Pay Rent On | WareOnGo",
    "description": "Carpet, built-up and super built-up area in warehouse leases: what each includes, the loading factor, why RERA's carpet-area rule doesn't apply, and how to compare quotes on effective rate per usable sqft.",
    "summary": "Carpet area is the floor you can actually use. Built-up area adds walls, columns and built-in rooms - this is what most warehouse owners quote. Super built-up area further adds your share of common areas; the addition on top of carpet area is the loading factor. There is no RERA-style rule for warehouse leases, so the \"chargeable area\" is whatever the lease says it is. Ask which area the ₹/sqft applies to, measure the carpet area yourself, and compare quotes on the effective rate per usable sqft, not the headline rate.",
    "published": "2026-07-03",
    "updated": "2026-07-03",
    "keywords": [
      "carpet area vs built-up area warehouse",
      "warehouse carpet area",
      "super built-up area warehouse",
      "loading factor warehouse",
      "chargeable area warehouse lease",
      "warehouse rent per sqft basis"
    ],
    "blocks": [
      {
        "kind": "p",
        "text": "Lease a 50,000 sqft warehouse and you will not get 50,000 sqft of storage. Somewhere between the number on the term sheet and the floor you can actually rack, a few thousand square feet quietly disappear. Rent, deposit, and escalation are all calculated on the bigger number. Your racking plan runs on the smaller one."
      },
      {
        "kind": "p",
        "text": "This is one of the most common ways occupiers overpay - not because anyone lied, but because nobody asked which area the ₹/sqft applies to. Here's how the three areas work, why warehousing is looser about them than housing, and how to compare quotes so a cheaper-looking warehouse doesn't turn out to be the expensive one."
      },
      {
        "kind": "h2",
        "text": "The three terms used to define warehouse area:"
      },
      {
        "kind": "p",
        "text": "Carpet area is the floor you can actually use - measured wall to wall, inside the building. If you could lay carpet on it (or in our world, put a pallet on it), it counts. Columns, walls, and built-in rooms don't."
      },
      {
        "kind": "p",
        "text": "Built-up area is the carpet area plus everything the structure itself takes up: external and internal walls, columns, the office block, toilets, staircases, electrical and pump rooms. This is the area most warehouse owners quote."
      },
      {
        "kind": "p",
        "text": "Super built-up area adds your proportionate share of common areas. In a warehousing park, that can mean internal roads, common truck aprons, the security cabin, and shared facilities. The addition on top of carpet area is what the market calls the loading factor."
      },
      {
        "kind": "p",
        "text": "Same warehouse, three different numbers. And the rate per sqft means nothing until you know which of the three it's multiplied by."
      },
      {
        "kind": "h2",
        "text": "Why this matters more in warehousing than in residential real estate:"
      },
      {
        "kind": "p",
        "text": "Home buyers have protection here: RERA forced residential developers to quote carpet area, with a legal definition behind it. A warehouse lease gets no such rule. It's a private contract between you and the owner, and the \"chargeable area\" is whatever the lease says it is."
      },
      {
        "kind": "p",
        "text": "So two quotes can both say ₹20/sqft and cost very different money. One owner quotes on carpet. Another quotes on super built-up with the truck apron factored in. On paper they're identical. On your balance sheet they're not."
      },
      {
        "kind": "h2",
        "text": "How you might get conned by owners, with an example:"
      },
      {
        "kind": "p",
        "text": "Say you're comparing two options for a 3PL operation:"
      },
      {
        "kind": "p",
        "text": "Warehouse A: quoted 50,000 sqft (built-up) at ₹20/sqft = ₹10,00,000/month. You measure the carpet area: 43,000 sqft. Your effective rate on usable floor is ₹23.3/sqft."
      },
      {
        "kind": "p",
        "text": "Warehouse B: quoted 45,000 sqft (carpet) at ₹22/sqft = ₹9,90,000/month. Effective rate on usable floor: ₹22/sqft - for more usable space than Warehouse A."
      },
      {
        "kind": "p",
        "text": "Warehouse B looked more expensive. It's cheaper, and bigger where it counts."
      },
      {
        "kind": "p",
        "text": "The gap doesn't stop at rent. The deposit is a multiple of monthly rent, so it's inflated by the same factor. Escalation is a percentage of rent, so the gap widens every escalation cycle. Over a five-year lock-in, a few rupees of hidden loading per sqft adds up to a number worth negotiating hard for."
      },
      {
        "kind": "h2",
        "text": "Where the area is used up in a warehouse:"
      },
      {
        "kind": "p",
        "text": "Worth knowing before a site visit, so you can see it with your own eyes:"
      },
      {
        "kind": "ul",
        "items": [
          "Structure. Walls and columns. This is where construction type matters: a PEB warehouse gives you wide column-free spans of 20-30 metres or more, while an older RCC godown has a forest of columns eating into carpet area and breaking up your racking grid. (More in our PEB vs RCC guide.)",
          "Built-in rooms. The office block, toilets, guard room, electrical room, pump room. Useful - but ask whether you're paying warehouse rates for office space you don't need.",
          "Common-area loading. In parks, your share of roads, aprons, and shared facilities. Ask for the loading percentage in writing and what it covers."
        ]
      },
      {
        "kind": "p",
        "text": "And one thing area never captures: height. A 12-metre Grade A warehouse racked five pallets high holds roughly twice as much as a 6-metre shed with the same footprint. Which is why the sharpest occupiers compare cost per pallet position, not cost per sqft - a warehouse with less carpet area can still be the cheaper building per pallet stored. (More in our Grade A vs B guide.)"
      },
      {
        "kind": "h2",
        "text": "Five things to do before you sign"
      },
      {
        "kind": "ol",
        "items": [
          "Ask which area the rate applies to. Carpet, built-up, or super built-up. If the answer is vague, get it clarified and consider that in your evaluation of the property.",
          "Get \"chargeable area\" defined in the lease. The number, the basis, and how it was measured. Not just the brochure figure.",
          "Measure the carpet area yourself. Physically, on site. While you're at it, measure clear height at the lowest obstruction - beam, duct, or sprinkler - not the ridge. Space blocked is space you cannot use.",
          "Recompute every quote on usable area before comparing. Rank options on effective rate, not headline rate.",
          "Check if the deposit and escalation are calculated on the same defined area. The lease should use one number everywhere."
        ]
      },
      {
        "kind": "h2",
        "text": "How we handle this at WareOnGo"
      },
      {
        "kind": "p",
        "text": "Every warehouse we share is verified physically for specs before it reaches you - including what the usable floor actually measures. Then we negotiate the full term sheet on that basis: rent, deposit, escalation, lock-in. Our clients typically save 8-12% on commercials."
      },
      {
        "kind": "p",
        "text": "Chargeable area itself is negotiable more often than people think. In Hoskote, a client of ours needed exactly 20,000 sqft. The right warehouse was 25,000. We got the owner to charge for only 20,000 - because he trusted us, and because we committed to finding a tenant for the remaining 5,000 sqft. The area on the invoice is a term like any other. It can be negotiated."
      },
      {
        "kind": "p",
        "text": "Looking for space? Browse verified options - warehouse for rent in Bangalore, Hyderabad, Mumbai and Bhiwandi - or write to sales@wareongo.com / +91 7400184225. You get a curated shortlist, and you only pay when you close."
      }
    ],
    "faqs": [
      {
        "a": "Carpet area is the usable floor measured inside the walls. Built-up area adds the walls, columns, and built-in rooms (office, toilets, staircases). Super built-up area further adds your share of common areas like roads and aprons in a park.",
        "q": "What is the difference between carpet area and built-up area?"
      },
      {
        "a": "There's no fixed rule. It's whatever the lease defines as chargeable area - most owners quote on built-up or super built-up. Always ask, and get the basis written into the lease.",
        "q": "Is warehouse rent charged on carpet area or built-up area?"
      },
      {
        "a": "The percentage added on top of the carpet area to arrive at the chargeable area. It covers structure and common areas. A higher loading means less usable floor per rupee of rent.",
        "q": "What is a loading factor?"
      },
      {
        "a": "No. RERA's carpet-area protections were built for property buyers. A warehouse lease is a private contract - the lease document decides which area you pay on, so the definition has to be negotiated in.",
        "q": "Does RERA's carpet-area rule apply to warehouse leases?"
      }
    ],
    "related": [
      "warehouse-rent-india-guide",
      "peb-vs-rcc-warehouse",
      "grade-a-warehouse-india"
    ]
  }
];
