// AUTO-GENERATED by scripts/generate-locations.mjs — do not edit by hand.
// Regenerated on every `npm run build`. Source: backend warehouses API.

export interface LocationSummary {
  canonical: string;
  slug: string;
  count: number;
}

export interface LocationsByType {
  PEB: LocationSummary[];
  RCC: LocationSummary[];
}

export const CITIES: LocationSummary[] = [
  {
    "canonical": "Ahmedabad",
    "slug": "ahmedabad",
    "count": 10
  },
  {
    "canonical": "Ahmedadbad",
    "slug": "ahmedadbad",
    "count": 1
  },
  {
    "canonical": "Ahmednagar",
    "slug": "ahmednagar",
    "count": 1
  },
  {
    "canonical": "Aligarh",
    "slug": "aligarh",
    "count": 2
  },
  {
    "canonical": "Alipur",
    "slug": "alipur",
    "count": 3
  },
  {
    "canonical": "Ambattur",
    "slug": "ambattur",
    "count": 1
  },
  {
    "canonical": "Athur",
    "slug": "athur",
    "count": 1
  },
  {
    "canonical": "Aurangabad",
    "slug": "aurangabad",
    "count": 1
  },
  {
    "canonical": "Baka Kapsi",
    "slug": "baka-kapsi",
    "count": 1
  },
  {
    "canonical": "Bamnoli",
    "slug": "bamnoli",
    "count": 4
  },
  {
    "canonical": "Bandikavanoor",
    "slug": "bandikavanoor",
    "count": 1
  },
  {
    "canonical": "Banglore",
    "slug": "banglore",
    "count": 1
  },
  {
    "canonical": "Barabanki",
    "slug": "barabanki",
    "count": 1
  },
  {
    "canonical": "Bengaluru",
    "slug": "bengaluru",
    "count": 400
  },
  {
    "canonical": "Bhadua",
    "slug": "bhadua",
    "count": 1
  },
  {
    "canonical": "Bhubaneswar",
    "slug": "bhubaneswar",
    "count": 1
  },
  {
    "canonical": "Bijwasan",
    "slug": "bijwasan",
    "count": 1
  },
  {
    "canonical": "Chennai",
    "slug": "chennai",
    "count": 2
  },
  {
    "canonical": "Chhak",
    "slug": "chhak",
    "count": 1
  },
  {
    "canonical": "Dadri",
    "slug": "dadri",
    "count": 3
  },
  {
    "canonical": "Delhi",
    "slug": "delhi",
    "count": 5
  },
  {
    "canonical": "Ecotech 11",
    "slug": "ecotech-11",
    "count": 1
  },
  {
    "canonical": "Faridabad",
    "slug": "faridabad",
    "count": 2
  },
  {
    "canonical": "Farukhnagar",
    "slug": "farukhnagar",
    "count": 1
  },
  {
    "canonical": "Gerugambakkm",
    "slug": "gerugambakkm",
    "count": 1
  },
  {
    "canonical": "Ghaziabad",
    "slug": "ghaziabad",
    "count": 13
  },
  {
    "canonical": "Goa",
    "slug": "goa",
    "count": 2
  },
  {
    "canonical": "Greater Noida",
    "slug": "greater-noida",
    "count": 6
  },
  {
    "canonical": "Guntur",
    "slug": "guntur",
    "count": 5
  },
  {
    "canonical": "Gurugram",
    "slug": "gurugram",
    "count": 30
  },
  {
    "canonical": "Guwahati",
    "slug": "guwahati",
    "count": 6
  },
  {
    "canonical": "Hiran Kudna",
    "slug": "hiran-kudna",
    "count": 1
  },
  {
    "canonical": "Hosur",
    "slug": "hosur",
    "count": 16
  },
  {
    "canonical": "Howrah",
    "slug": "howrah",
    "count": 4
  },
  {
    "canonical": "Hubli",
    "slug": "hubli",
    "count": 5
  },
  {
    "canonical": "Hyderabad",
    "slug": "hyderabad",
    "count": 27
  },
  {
    "canonical": "Indore",
    "slug": "indore",
    "count": 3
  },
  {
    "canonical": "Jaipur",
    "slug": "jaipur",
    "count": 3
  },
  {
    "canonical": "Jalgaon",
    "slug": "jalgaon",
    "count": 1
  },
  {
    "canonical": "Janla",
    "slug": "janla",
    "count": 1
  },
  {
    "canonical": "Kancheepuram",
    "slug": "kancheepuram",
    "count": 1
  },
  {
    "canonical": "Kanpur",
    "slug": "kanpur",
    "count": 2
  },
  {
    "canonical": "Karolbag",
    "slug": "karolbag",
    "count": 1
  },
  {
    "canonical": "Kolar",
    "slug": "kolar",
    "count": 1
  },
  {
    "canonical": "Kolkata",
    "slug": "kolkata",
    "count": 15
  },
  {
    "canonical": "Kompally",
    "slug": "kompally",
    "count": 2
  },
  {
    "canonical": "Laxmipuram",
    "slug": "laxmipuram",
    "count": 1
  },
  {
    "canonical": "Lucknow",
    "slug": "lucknow",
    "count": 4
  },
  {
    "canonical": "Maduranthakam",
    "slug": "maduranthakam",
    "count": 1
  },
  {
    "canonical": "Mangalore",
    "slug": "mangalore",
    "count": 1
  },
  {
    "canonical": "Mumbai",
    "slug": "mumbai",
    "count": 1
  },
  {
    "canonical": "Mundka",
    "slug": "mundka",
    "count": 1
  },
  {
    "canonical": "Nacharam",
    "slug": "nacharam",
    "count": 1
  },
  {
    "canonical": "Nadiad",
    "slug": "nadiad",
    "count": 2
  },
  {
    "canonical": "Nagpur",
    "slug": "nagpur",
    "count": 3
  },
  {
    "canonical": "Nashik",
    "slug": "nashik",
    "count": 1
  },
  {
    "canonical": "Nellore",
    "slug": "nellore",
    "count": 1
  },
  {
    "canonical": "Nh -06highway",
    "slug": "nh--06highway",
    "count": 1
  },
  {
    "canonical": "Noida",
    "slug": "noida",
    "count": 7
  },
  {
    "canonical": "Ogalapada",
    "slug": "ogalapada",
    "count": 1
  },
  {
    "canonical": "Okhla",
    "slug": "okhla",
    "count": 2
  },
  {
    "canonical": "Pammathukulam",
    "slug": "pammathukulam",
    "count": 1
  },
  {
    "canonical": "Patna",
    "slug": "patna",
    "count": 9
  },
  {
    "canonical": "Pune",
    "slug": "pune",
    "count": 1
  },
  {
    "canonical": "Raipur",
    "slug": "raipur",
    "count": 2
  },
  {
    "canonical": "Rajkot",
    "slug": "rajkot",
    "count": 5
  },
  {
    "canonical": "Rajoukri",
    "slug": "rajoukri",
    "count": 1
  },
  {
    "canonical": "Red Hills",
    "slug": "red-hills",
    "count": 1
  },
  {
    "canonical": "Rudrapur",
    "slug": "rudrapur",
    "count": 1
  },
  {
    "canonical": "Salem",
    "slug": "salem",
    "count": 4
  },
  {
    "canonical": "Sector 77, Gurugram",
    "slug": "sector-77-gurugram",
    "count": 1
  },
  {
    "canonical": "Sector 78, Badshahpur",
    "slug": "sector-78-badshahpur",
    "count": 1
  },
  {
    "canonical": "Sengadu",
    "slug": "sengadu",
    "count": 1
  },
  {
    "canonical": "Shamshabad",
    "slug": "shamshabad",
    "count": 1
  },
  {
    "canonical": "Shanmugapadmavathy Nagar",
    "slug": "shanmugapadmavathy-nagar",
    "count": 1
  },
  {
    "canonical": "Sholavaram",
    "slug": "sholavaram",
    "count": 1
  },
  {
    "canonical": "Solapur",
    "slug": "solapur",
    "count": 2
  },
  {
    "canonical": "Sriperumbudur",
    "slug": "sriperumbudur",
    "count": 1
  },
  {
    "canonical": "Surat",
    "slug": "surat",
    "count": 6
  },
  {
    "canonical": "Thane",
    "slug": "thane",
    "count": 3
  },
  {
    "canonical": "Tumkur",
    "slug": "tumkur",
    "count": 2
  },
  {
    "canonical": "Udyog Kunj",
    "slug": "udyog-kunj",
    "count": 1
  },
  {
    "canonical": "Vijayawada",
    "slug": "vijayawada",
    "count": 3
  },
  {
    "canonical": "Vishakapatnam",
    "slug": "vishakapatnam",
    "count": 1
  },
  {
    "canonical": "Vizag",
    "slug": "vizag",
    "count": 3
  }
];

export const STATES: LocationSummary[] = [
  {
    "canonical": "501218",
    "slug": "501218",
    "count": 1
  },
  {
    "canonical": "Andhra Pradesh",
    "slug": "andhra-pradesh",
    "count": 13
  },
  {
    "canonical": "Assam",
    "slug": "assam",
    "count": 6
  },
  {
    "canonical": "Bhubaneswar",
    "slug": "bhubaneswar",
    "count": 1
  },
  {
    "canonical": "Bihar",
    "slug": "bihar",
    "count": 9
  },
  {
    "canonical": "Chattisgarh",
    "slug": "chattisgarh",
    "count": 1
  },
  {
    "canonical": "Chhattisgarh",
    "slug": "chhattisgarh",
    "count": 1
  },
  {
    "canonical": "Delhi",
    "slug": "delhi",
    "count": 19
  },
  {
    "canonical": "Goa",
    "slug": "goa",
    "count": 2
  },
  {
    "canonical": "Gujarat",
    "slug": "gujarat",
    "count": 24
  },
  {
    "canonical": "Haryana",
    "slug": "haryana",
    "count": 35
  },
  {
    "canonical": "Karanataka",
    "slug": "karanataka",
    "count": 1
  },
  {
    "canonical": "Karnataka",
    "slug": "karnataka",
    "count": 409
  },
  {
    "canonical": "Kolkata",
    "slug": "kolkata",
    "count": 5
  },
  {
    "canonical": "Madhya Pradesh",
    "slug": "madhya-pradesh",
    "count": 3
  },
  {
    "canonical": "Maharashtra",
    "slug": "maharashtra",
    "count": 16
  },
  {
    "canonical": "Odisha",
    "slug": "odisha",
    "count": 4
  },
  {
    "canonical": "Rajasthan",
    "slug": "rajasthan",
    "count": 3
  },
  {
    "canonical": "Tamil Nadu",
    "slug": "tamil-nadu",
    "count": 31
  },
  {
    "canonical": "Tamilnadu",
    "slug": "tamilnadu",
    "count": 4
  },
  {
    "canonical": "Telangana",
    "slug": "telangana",
    "count": 30
  },
  {
    "canonical": "Uttar Pradesh",
    "slug": "uttar-pradesh",
    "count": 40
  },
  {
    "canonical": "West Bengal",
    "slug": "west-bengal",
    "count": 15
  }
];

export const CITIES_BY_TYPE: LocationsByType = {
  "PEB": [
    {
      "canonical": "Ahmedabad",
      "slug": "ahmedabad",
      "count": 9
    },
    {
      "canonical": "Ahmedadbad",
      "slug": "ahmedadbad",
      "count": 1
    },
    {
      "canonical": "Ahmednagar",
      "slug": "ahmednagar",
      "count": 1
    },
    {
      "canonical": "Alipur",
      "slug": "alipur",
      "count": 3
    },
    {
      "canonical": "Athur",
      "slug": "athur",
      "count": 1
    },
    {
      "canonical": "Barabanki",
      "slug": "barabanki",
      "count": 1
    },
    {
      "canonical": "Bengaluru",
      "slug": "bengaluru",
      "count": 268
    },
    {
      "canonical": "Bhadua",
      "slug": "bhadua",
      "count": 1
    },
    {
      "canonical": "Chhak",
      "slug": "chhak",
      "count": 1
    },
    {
      "canonical": "Dadri",
      "slug": "dadri",
      "count": 3
    },
    {
      "canonical": "Delhi",
      "slug": "delhi",
      "count": 4
    },
    {
      "canonical": "Faridabad",
      "slug": "faridabad",
      "count": 1
    },
    {
      "canonical": "Ghaziabad",
      "slug": "ghaziabad",
      "count": 7
    },
    {
      "canonical": "Goa",
      "slug": "goa",
      "count": 1
    },
    {
      "canonical": "Greater Noida",
      "slug": "greater-noida",
      "count": 4
    },
    {
      "canonical": "Guntur",
      "slug": "guntur",
      "count": 3
    },
    {
      "canonical": "Gurugram",
      "slug": "gurugram",
      "count": 25
    },
    {
      "canonical": "Guwahati",
      "slug": "guwahati",
      "count": 6
    },
    {
      "canonical": "Hosur",
      "slug": "hosur",
      "count": 13
    },
    {
      "canonical": "Hubli",
      "slug": "hubli",
      "count": 4
    },
    {
      "canonical": "Hyderabad",
      "slug": "hyderabad",
      "count": 11
    },
    {
      "canonical": "Indore",
      "slug": "indore",
      "count": 2
    },
    {
      "canonical": "Jaipur",
      "slug": "jaipur",
      "count": 3
    },
    {
      "canonical": "Jalgaon",
      "slug": "jalgaon",
      "count": 1
    },
    {
      "canonical": "Kancheepuram",
      "slug": "kancheepuram",
      "count": 1
    },
    {
      "canonical": "Kanpur",
      "slug": "kanpur",
      "count": 1
    },
    {
      "canonical": "Karolbag",
      "slug": "karolbag",
      "count": 1
    },
    {
      "canonical": "Kolar",
      "slug": "kolar",
      "count": 1
    },
    {
      "canonical": "Kolkata",
      "slug": "kolkata",
      "count": 14
    },
    {
      "canonical": "Laxmipuram",
      "slug": "laxmipuram",
      "count": 1
    },
    {
      "canonical": "Lucknow",
      "slug": "lucknow",
      "count": 1
    },
    {
      "canonical": "Mumbai",
      "slug": "mumbai",
      "count": 1
    },
    {
      "canonical": "Nacharam",
      "slug": "nacharam",
      "count": 1
    },
    {
      "canonical": "Nadiad",
      "slug": "nadiad",
      "count": 1
    },
    {
      "canonical": "Nagpur",
      "slug": "nagpur",
      "count": 2
    },
    {
      "canonical": "Nellore",
      "slug": "nellore",
      "count": 1
    },
    {
      "canonical": "Noida",
      "slug": "noida",
      "count": 6
    },
    {
      "canonical": "Patna",
      "slug": "patna",
      "count": 8
    },
    {
      "canonical": "Pune",
      "slug": "pune",
      "count": 1
    },
    {
      "canonical": "Raipur",
      "slug": "raipur",
      "count": 1
    },
    {
      "canonical": "Rajkot",
      "slug": "rajkot",
      "count": 4
    },
    {
      "canonical": "Rajoukri",
      "slug": "rajoukri",
      "count": 1
    },
    {
      "canonical": "Red Hills",
      "slug": "red-hills",
      "count": 1
    },
    {
      "canonical": "Salem",
      "slug": "salem",
      "count": 2
    },
    {
      "canonical": "Sector 77, Gurugram",
      "slug": "sector-77-gurugram",
      "count": 1
    },
    {
      "canonical": "Sector 78, Badshahpur",
      "slug": "sector-78-badshahpur",
      "count": 1
    },
    {
      "canonical": "Sengadu",
      "slug": "sengadu",
      "count": 1
    },
    {
      "canonical": "Shamshabad",
      "slug": "shamshabad",
      "count": 1
    },
    {
      "canonical": "Sholavaram",
      "slug": "sholavaram",
      "count": 1
    },
    {
      "canonical": "Solapur",
      "slug": "solapur",
      "count": 2
    },
    {
      "canonical": "Sriperumbudur",
      "slug": "sriperumbudur",
      "count": 1
    },
    {
      "canonical": "Surat",
      "slug": "surat",
      "count": 2
    },
    {
      "canonical": "Thane",
      "slug": "thane",
      "count": 3
    },
    {
      "canonical": "Vijayawada",
      "slug": "vijayawada",
      "count": 2
    },
    {
      "canonical": "Vishakapatnam",
      "slug": "vishakapatnam",
      "count": 1
    },
    {
      "canonical": "Vizag",
      "slug": "vizag",
      "count": 2
    }
  ],
  "RCC": [
    {
      "canonical": "Aligarh",
      "slug": "aligarh",
      "count": 2
    },
    {
      "canonical": "Ambattur",
      "slug": "ambattur",
      "count": 1
    },
    {
      "canonical": "Aurangabad",
      "slug": "aurangabad",
      "count": 1
    },
    {
      "canonical": "Bamnoli",
      "slug": "bamnoli",
      "count": 1
    },
    {
      "canonical": "Banglore",
      "slug": "banglore",
      "count": 1
    },
    {
      "canonical": "Bengaluru",
      "slug": "bengaluru",
      "count": 51
    },
    {
      "canonical": "Delhi",
      "slug": "delhi",
      "count": 1
    },
    {
      "canonical": "Faridabad",
      "slug": "faridabad",
      "count": 1
    },
    {
      "canonical": "Ghaziabad",
      "slug": "ghaziabad",
      "count": 3
    },
    {
      "canonical": "Goa",
      "slug": "goa",
      "count": 1
    },
    {
      "canonical": "Guntur",
      "slug": "guntur",
      "count": 1
    },
    {
      "canonical": "Gurugram",
      "slug": "gurugram",
      "count": 3
    },
    {
      "canonical": "Hiran Kudna",
      "slug": "hiran-kudna",
      "count": 1
    },
    {
      "canonical": "Howrah",
      "slug": "howrah",
      "count": 1
    },
    {
      "canonical": "Hubli",
      "slug": "hubli",
      "count": 1
    },
    {
      "canonical": "Hyderabad",
      "slug": "hyderabad",
      "count": 10
    },
    {
      "canonical": "Indore",
      "slug": "indore",
      "count": 1
    },
    {
      "canonical": "Kanpur",
      "slug": "kanpur",
      "count": 1
    },
    {
      "canonical": "Kolkata",
      "slug": "kolkata",
      "count": 1
    },
    {
      "canonical": "Kompally",
      "slug": "kompally",
      "count": 2
    },
    {
      "canonical": "Lucknow",
      "slug": "lucknow",
      "count": 2
    },
    {
      "canonical": "Mangalore",
      "slug": "mangalore",
      "count": 1
    },
    {
      "canonical": "Nadiad",
      "slug": "nadiad",
      "count": 1
    },
    {
      "canonical": "Nashik",
      "slug": "nashik",
      "count": 1
    },
    {
      "canonical": "Noida",
      "slug": "noida",
      "count": 1
    },
    {
      "canonical": "Okhla",
      "slug": "okhla",
      "count": 2
    },
    {
      "canonical": "Pammathukulam",
      "slug": "pammathukulam",
      "count": 1
    },
    {
      "canonical": "Raipur",
      "slug": "raipur",
      "count": 1
    },
    {
      "canonical": "Surat",
      "slug": "surat",
      "count": 4
    },
    {
      "canonical": "Udyog Kunj",
      "slug": "udyog-kunj",
      "count": 1
    },
    {
      "canonical": "Vijayawada",
      "slug": "vijayawada",
      "count": 1
    },
    {
      "canonical": "Vizag",
      "slug": "vizag",
      "count": 1
    }
  ]
};

export const STATES_BY_TYPE: LocationsByType = {
  "PEB": [
    {
      "canonical": "Andhra Pradesh",
      "slug": "andhra-pradesh",
      "count": 9
    },
    {
      "canonical": "Assam",
      "slug": "assam",
      "count": 6
    },
    {
      "canonical": "Bihar",
      "slug": "bihar",
      "count": 8
    },
    {
      "canonical": "Chhattisgarh",
      "slug": "chhattisgarh",
      "count": 1
    },
    {
      "canonical": "Delhi",
      "slug": "delhi",
      "count": 9
    },
    {
      "canonical": "Goa",
      "slug": "goa",
      "count": 1
    },
    {
      "canonical": "Gujarat",
      "slug": "gujarat",
      "count": 17
    },
    {
      "canonical": "Haryana",
      "slug": "haryana",
      "count": 28
    },
    {
      "canonical": "Karanataka",
      "slug": "karanataka",
      "count": 1
    },
    {
      "canonical": "Karnataka",
      "slug": "karnataka",
      "count": 272
    },
    {
      "canonical": "Kolkata",
      "slug": "kolkata",
      "count": 1
    },
    {
      "canonical": "Madhya Pradesh",
      "slug": "madhya-pradesh",
      "count": 2
    },
    {
      "canonical": "Maharashtra",
      "slug": "maharashtra",
      "count": 11
    },
    {
      "canonical": "Odisha",
      "slug": "odisha",
      "count": 1
    },
    {
      "canonical": "Rajasthan",
      "slug": "rajasthan",
      "count": 3
    },
    {
      "canonical": "Tamil Nadu",
      "slug": "tamil-nadu",
      "count": 21
    },
    {
      "canonical": "Tamilnadu",
      "slug": "tamilnadu",
      "count": 1
    },
    {
      "canonical": "Telangana",
      "slug": "telangana",
      "count": 13
    },
    {
      "canonical": "Uttar Pradesh",
      "slug": "uttar-pradesh",
      "count": 23
    },
    {
      "canonical": "West Bengal",
      "slug": "west-bengal",
      "count": 14
    }
  ],
  "RCC": [
    {
      "canonical": "Andhra Pradesh",
      "slug": "andhra-pradesh",
      "count": 3
    },
    {
      "canonical": "Chattisgarh",
      "slug": "chattisgarh",
      "count": 1
    },
    {
      "canonical": "Delhi",
      "slug": "delhi",
      "count": 5
    },
    {
      "canonical": "Goa",
      "slug": "goa",
      "count": 1
    },
    {
      "canonical": "Gujarat",
      "slug": "gujarat",
      "count": 5
    },
    {
      "canonical": "Haryana",
      "slug": "haryana",
      "count": 4
    },
    {
      "canonical": "Karnataka",
      "slug": "karnataka",
      "count": 54
    },
    {
      "canonical": "Kolkata",
      "slug": "kolkata",
      "count": 1
    },
    {
      "canonical": "Madhya Pradesh",
      "slug": "madhya-pradesh",
      "count": 1
    },
    {
      "canonical": "Maharashtra",
      "slug": "maharashtra",
      "count": 2
    },
    {
      "canonical": "Tamil Nadu",
      "slug": "tamil-nadu",
      "count": 2
    },
    {
      "canonical": "Telangana",
      "slug": "telangana",
      "count": 12
    },
    {
      "canonical": "Uttar Pradesh",
      "slug": "uttar-pradesh",
      "count": 10
    },
    {
      "canonical": "West Bengal",
      "slug": "west-bengal",
      "count": 1
    }
  ]
};
