// AUTO-GENERATED by scripts/generate-location-pages.mjs — do not edit by hand.
// Regenerated on every `npm run build`. Source: backend /location-pages
// (CMS-managed). Types live in ./locationPages.ts, which re-exports this data.
//
// An empty array is the normal starting state, and it is not a failure: every
// city/state overview is emitted only after an editor publishes content for it.
import type { LocationPageContent } from './locationPages';

export const locationPages: LocationPageContent[] = [];
