// AUTO-GENERATED by scripts/generate-locations.mjs — do not edit by hand.
// Regenerated on every `npm run build`. Sources: backend warehouses, locations and micromarkets APIs.

export interface LocationSummary {
  canonical: string;
  slug: string;
  count: number;
}

export interface LocationsByType {
  PEB: LocationSummary[];
  RCC: LocationSummary[];
}

export interface MicromarketSummary extends LocationSummary {
  parentCity: string;
  /** The {city} in /listings/city/{city}/{slug}. */
  citySlug: string;
}

// Listings a city needs before its page is advertised in the footer or the
// sitemap. Mirrors CITY_MIN_LISTINGS in scripts/lib/locations.mjs, so the two
// surfaces can't drift apart.
export const CITY_MIN_LISTINGS = 3;

export const CITIES: LocationSummary[] = [
  {
    "canonical": "Ahilyanagar",
    "slug": "ahilyanagar",
    "count": 1
  },
  {
    "canonical": "Ahmedabad",
    "slug": "ahmedabad",
    "count": 59
  },
  {
    "canonical": "Ahmednagar",
    "slug": "ahmednagar",
    "count": 2
  },
  {
    "canonical": "Aligarh",
    "slug": "aligarh",
    "count": 2
  },
  {
    "canonical": "Ambala",
    "slug": "ambala",
    "count": 1
  },
  {
    "canonical": "Anakapalli",
    "slug": "anakapalli",
    "count": 1
  },
  {
    "canonical": "Anantapur",
    "slug": "anantapur",
    "count": 4
  },
  {
    "canonical": "Aurangabad",
    "slug": "aurangabad",
    "count": 6
  },
  {
    "canonical": "Barabanki",
    "slug": "barabanki",
    "count": 1
  },
  {
    "canonical": "Belagavi",
    "slug": "belagavi",
    "count": 1
  },
  {
    "canonical": "Bengaluru",
    "slug": "bengaluru",
    "count": 576
  },
  {
    "canonical": "Bhavnagar",
    "slug": "bhavnagar",
    "count": 1
  },
  {
    "canonical": "Bhiwadi",
    "slug": "bhiwadi",
    "count": 8
  },
  {
    "canonical": "Bhiwandi",
    "slug": "bhiwandi",
    "count": 58
  },
  {
    "canonical": "Bhongir",
    "slug": "bhongir",
    "count": 1
  },
  {
    "canonical": "Bhopal",
    "slug": "bhopal",
    "count": 7
  },
  {
    "canonical": "Bhubaneswar",
    "slug": "bhubaneswar",
    "count": 19
  },
  {
    "canonical": "Bilaspur",
    "slug": "bilaspur",
    "count": 2
  },
  {
    "canonical": "Chandauli",
    "slug": "chandauli",
    "count": 2
  },
  {
    "canonical": "Chandigarh",
    "slug": "chandigarh",
    "count": 4
  },
  {
    "canonical": "Chennai",
    "slug": "chennai",
    "count": 58
  },
  {
    "canonical": "Chhatrapati Sambhajinagar / Aurangabad",
    "slug": "chhatrapati-sambhajinagar--aurangabad",
    "count": 3
  },
  {
    "canonical": "Coimbatore",
    "slug": "coimbatore",
    "count": 30
  },
  {
    "canonical": "Cuttack",
    "slug": "cuttack",
    "count": 4
  },
  {
    "canonical": "Dadri",
    "slug": "dadri",
    "count": 9
  },
  {
    "canonical": "Dahej",
    "slug": "dahej",
    "count": 3
  },
  {
    "canonical": "Delhi",
    "slug": "delhi",
    "count": 58
  },
  {
    "canonical": "Dharuhera",
    "slug": "dharuhera",
    "count": 5
  },
  {
    "canonical": "Ernakulam",
    "slug": "ernakulam",
    "count": 10
  },
  {
    "canonical": "Faridabad",
    "slug": "faridabad",
    "count": 3
  },
  {
    "canonical": "Gandhidham",
    "slug": "gandhidham",
    "count": 1
  },
  {
    "canonical": "Gandhinagar",
    "slug": "gandhinagar",
    "count": 1
  },
  {
    "canonical": "Ghaziabad",
    "slug": "ghaziabad",
    "count": 45
  },
  {
    "canonical": "Goa",
    "slug": "goa",
    "count": 2
  },
  {
    "canonical": "Guntur",
    "slug": "guntur",
    "count": 10
  },
  {
    "canonical": "Gurugram",
    "slug": "gurugram",
    "count": 137
  },
  {
    "canonical": "Guwahati",
    "slug": "guwahati",
    "count": 13
  },
  {
    "canonical": "Gwalior",
    "slug": "gwalior",
    "count": 2
  },
  {
    "canonical": "Hapur",
    "slug": "hapur",
    "count": 2
  },
  {
    "canonical": "Hosur",
    "slug": "hosur",
    "count": 32
  },
  {
    "canonical": "Hubli",
    "slug": "hubli",
    "count": 8
  },
  {
    "canonical": "Hyderabad",
    "slug": "hyderabad",
    "count": 138
  },
  {
    "canonical": "Indore",
    "slug": "indore",
    "count": 33
  },
  {
    "canonical": "Jabalpur",
    "slug": "jabalpur",
    "count": 1
  },
  {
    "canonical": "Jaipur",
    "slug": "jaipur",
    "count": 31
  },
  {
    "canonical": "Jalandhar",
    "slug": "jalandhar",
    "count": 1
  },
  {
    "canonical": "Jalgaon",
    "slug": "jalgaon",
    "count": 1
  },
  {
    "canonical": "Jamnagar",
    "slug": "jamnagar",
    "count": 1
  },
  {
    "canonical": "Jodhpur",
    "slug": "jodhpur",
    "count": 6
  },
  {
    "canonical": "Jorhat",
    "slug": "jorhat",
    "count": 2
  },
  {
    "canonical": "Kanpur",
    "slug": "kanpur",
    "count": 5
  },
  {
    "canonical": "Karnal",
    "slug": "karnal",
    "count": 5
  },
  {
    "canonical": "Kharagpur",
    "slug": "kharagpur",
    "count": 1
  },
  {
    "canonical": "Kheda",
    "slug": "kheda",
    "count": 1
  },
  {
    "canonical": "Kochi",
    "slug": "kochi",
    "count": 10
  },
  {
    "canonical": "Kolar",
    "slug": "kolar",
    "count": 15
  },
  {
    "canonical": "Kolhapur",
    "slug": "kolhapur",
    "count": 6
  },
  {
    "canonical": "Kolkata",
    "slug": "kolkata",
    "count": 50
  },
  {
    "canonical": "Kollam",
    "slug": "kollam",
    "count": 1
  },
  {
    "canonical": "Krishnagiri",
    "slug": "krishnagiri",
    "count": 1
  },
  {
    "canonical": "Kumta",
    "slug": "kumta",
    "count": 1
  },
  {
    "canonical": "Lucknow",
    "slug": "lucknow",
    "count": 80
  },
  {
    "canonical": "Ludhiana",
    "slug": "ludhiana",
    "count": 9
  },
  {
    "canonical": "Madurai",
    "slug": "madurai",
    "count": 10
  },
  {
    "canonical": "Mahendragarh",
    "slug": "mahendragarh",
    "count": 1
  },
  {
    "canonical": "Manesar",
    "slug": "manesar",
    "count": 2
  },
  {
    "canonical": "Mangaluru",
    "slug": "mangaluru",
    "count": 19
  },
  {
    "canonical": "Mapusa",
    "slug": "mapusa",
    "count": 2
  },
  {
    "canonical": "Margao",
    "slug": "margao",
    "count": 1
  },
  {
    "canonical": "Medchal",
    "slug": "medchal",
    "count": 1
  },
  {
    "canonical": "Mehsana",
    "slug": "mehsana",
    "count": 1
  },
  {
    "canonical": "Mohali",
    "slug": "mohali",
    "count": 6
  },
  {
    "canonical": "Morbi",
    "slug": "morbi",
    "count": 1
  },
  {
    "canonical": "Mumbai",
    "slug": "mumbai",
    "count": 10
  },
  {
    "canonical": "Mundra",
    "slug": "mundra",
    "count": 3
  },
  {
    "canonical": "Mysore",
    "slug": "mysore",
    "count": 10
  },
  {
    "canonical": "Nadiad",
    "slug": "nadiad",
    "count": 1
  },
  {
    "canonical": "Nagpur",
    "slug": "nagpur",
    "count": 19
  },
  {
    "canonical": "Narmadapuram",
    "slug": "narmadapuram",
    "count": 1
  },
  {
    "canonical": "Navi Mumbai",
    "slug": "navi-mumbai",
    "count": 36
  },
  {
    "canonical": "Nellore",
    "slug": "nellore",
    "count": 2
  },
  {
    "canonical": "New Delhi",
    "slug": "new-delhi",
    "count": 2
  },
  {
    "canonical": "Noida",
    "slug": "noida",
    "count": 24
  },
  {
    "canonical": "North Goa",
    "slug": "north-goa",
    "count": 9
  },
  {
    "canonical": "Palakkad",
    "slug": "palakkad",
    "count": 1
  },
  {
    "canonical": "Palwal",
    "slug": "palwal",
    "count": 4
  },
  {
    "canonical": "Patiala",
    "slug": "patiala",
    "count": 1
  },
  {
    "canonical": "Patna",
    "slug": "patna",
    "count": 39
  },
  {
    "canonical": "Perambalur",
    "slug": "perambalur",
    "count": 1
  },
  {
    "canonical": "Puducherry",
    "slug": "puducherry",
    "count": 5
  },
  {
    "canonical": "Pune",
    "slug": "pune",
    "count": 50
  },
  {
    "canonical": "Raipur",
    "slug": "raipur",
    "count": 20
  },
  {
    "canonical": "Rajkot",
    "slug": "rajkot",
    "count": 27
  },
  {
    "canonical": "Rajpura",
    "slug": "rajpura",
    "count": 2
  },
  {
    "canonical": "Ranchi",
    "slug": "ranchi",
    "count": 7
  },
  {
    "canonical": "Rewari",
    "slug": "rewari",
    "count": 2
  },
  {
    "canonical": "Rohtak",
    "slug": "rohtak",
    "count": 1
  },
  {
    "canonical": "Rudrapur",
    "slug": "rudrapur",
    "count": 3
  },
  {
    "canonical": "Sagar",
    "slug": "sagar",
    "count": 1
  },
  {
    "canonical": "Salem",
    "slug": "salem",
    "count": 5
  },
  {
    "canonical": "Sanand",
    "slug": "sanand",
    "count": 1
  },
  {
    "canonical": "Satna",
    "slug": "satna",
    "count": 1
  },
  {
    "canonical": "Shamli",
    "slug": "shamli",
    "count": 1
  },
  {
    "canonical": "Shivamogga",
    "slug": "shivamogga",
    "count": 4
  },
  {
    "canonical": "Siliguri",
    "slug": "siliguri",
    "count": 1
  },
  {
    "canonical": "Silvassa",
    "slug": "silvassa",
    "count": 1
  },
  {
    "canonical": "Sivaganga",
    "slug": "sivaganga",
    "count": 1
  },
  {
    "canonical": "Solapur",
    "slug": "solapur",
    "count": 3
  },
  {
    "canonical": "Sonipat",
    "slug": "sonipat",
    "count": 7
  },
  {
    "canonical": "Surat",
    "slug": "surat",
    "count": 15
  },
  {
    "canonical": "Tepla",
    "slug": "tepla",
    "count": 4
  },
  {
    "canonical": "Tirupati",
    "slug": "tirupati",
    "count": 3
  },
  {
    "canonical": "Tiruppur",
    "slug": "tiruppur",
    "count": 2
  },
  {
    "canonical": "Tumakuru",
    "slug": "tumakuru",
    "count": 1
  },
  {
    "canonical": "Tumkur",
    "slug": "tumkur",
    "count": 2
  },
  {
    "canonical": "Vadodara",
    "slug": "vadodara",
    "count": 3
  },
  {
    "canonical": "Valsad",
    "slug": "valsad",
    "count": 3
  },
  {
    "canonical": "Varanasi",
    "slug": "varanasi",
    "count": 4
  },
  {
    "canonical": "Vijayawada",
    "slug": "vijayawada",
    "count": 50
  },
  {
    "canonical": "Villupuram",
    "slug": "villupuram",
    "count": 1
  },
  {
    "canonical": "Visakhapatnam",
    "slug": "visakhapatnam",
    "count": 24
  }
];

export const STATES: LocationSummary[] = [
  {
    "canonical": "Andhra Pradesh",
    "slug": "andhra-pradesh",
    "count": 94
  },
  {
    "canonical": "Assam",
    "slug": "assam",
    "count": 15
  },
  {
    "canonical": "Bihar",
    "slug": "bihar",
    "count": 39
  },
  {
    "canonical": "Chandigarh",
    "slug": "chandigarh",
    "count": 4
  },
  {
    "canonical": "Chhattisgarh",
    "slug": "chhattisgarh",
    "count": 20
  },
  {
    "canonical": "Dadra And Nagar Haveli And Daman And Diu",
    "slug": "dadra-and-nagar-haveli-and-daman-and-diu",
    "count": 1
  },
  {
    "canonical": "Delhi",
    "slug": "delhi",
    "count": 60
  },
  {
    "canonical": "Goa",
    "slug": "goa",
    "count": 14
  },
  {
    "canonical": "Gujarat",
    "slug": "gujarat",
    "count": 122
  },
  {
    "canonical": "Haryana",
    "slug": "haryana",
    "count": 170
  },
  {
    "canonical": "Jharkhand",
    "slug": "jharkhand",
    "count": 7
  },
  {
    "canonical": "Karnataka",
    "slug": "karnataka",
    "count": 637
  },
  {
    "canonical": "Kerala",
    "slug": "kerala",
    "count": 22
  },
  {
    "canonical": "Madhya Pradesh",
    "slug": "madhya-pradesh",
    "count": 46
  },
  {
    "canonical": "Maharashtra",
    "slug": "maharashtra",
    "count": 194
  },
  {
    "canonical": "Odisha",
    "slug": "odisha",
    "count": 23
  },
  {
    "canonical": "Puducherry",
    "slug": "puducherry",
    "count": 5
  },
  {
    "canonical": "Punjab",
    "slug": "punjab",
    "count": 23
  },
  {
    "canonical": "Rajasthan",
    "slug": "rajasthan",
    "count": 45
  },
  {
    "canonical": "Tamil Nadu",
    "slug": "tamil-nadu",
    "count": 142
  },
  {
    "canonical": "Telangana",
    "slug": "telangana",
    "count": 140
  },
  {
    "canonical": "Uttar Pradesh",
    "slug": "uttar-pradesh",
    "count": 175
  },
  {
    "canonical": "Uttarakhand",
    "slug": "uttarakhand",
    "count": 3
  },
  {
    "canonical": "West Bengal",
    "slug": "west-bengal",
    "count": 52
  }
];

export const CITIES_BY_TYPE: LocationsByType = {
  "PEB": [
    {
      "canonical": "Ahmedabad",
      "slug": "ahmedabad",
      "count": 40
    },
    {
      "canonical": "Ahmednagar",
      "slug": "ahmednagar",
      "count": 2
    },
    {
      "canonical": "Anantapur",
      "slug": "anantapur",
      "count": 3
    },
    {
      "canonical": "Aurangabad",
      "slug": "aurangabad",
      "count": 6
    },
    {
      "canonical": "Barabanki",
      "slug": "barabanki",
      "count": 1
    },
    {
      "canonical": "Belagavi",
      "slug": "belagavi",
      "count": 1
    },
    {
      "canonical": "Bengaluru",
      "slug": "bengaluru",
      "count": 343
    },
    {
      "canonical": "Bhiwadi",
      "slug": "bhiwadi",
      "count": 8
    },
    {
      "canonical": "Bhiwandi",
      "slug": "bhiwandi",
      "count": 43
    },
    {
      "canonical": "Bhopal",
      "slug": "bhopal",
      "count": 6
    },
    {
      "canonical": "Bhubaneswar",
      "slug": "bhubaneswar",
      "count": 5
    },
    {
      "canonical": "Chandauli",
      "slug": "chandauli",
      "count": 1
    },
    {
      "canonical": "Chennai",
      "slug": "chennai",
      "count": 40
    },
    {
      "canonical": "Chhatrapati Sambhajinagar / Aurangabad",
      "slug": "chhatrapati-sambhajinagar--aurangabad",
      "count": 1
    },
    {
      "canonical": "Coimbatore",
      "slug": "coimbatore",
      "count": 19
    },
    {
      "canonical": "Cuttack",
      "slug": "cuttack",
      "count": 4
    },
    {
      "canonical": "Dadri",
      "slug": "dadri",
      "count": 9
    },
    {
      "canonical": "Dahej",
      "slug": "dahej",
      "count": 3
    },
    {
      "canonical": "Delhi",
      "slug": "delhi",
      "count": 23
    },
    {
      "canonical": "Dharuhera",
      "slug": "dharuhera",
      "count": 4
    },
    {
      "canonical": "Ernakulam",
      "slug": "ernakulam",
      "count": 8
    },
    {
      "canonical": "Faridabad",
      "slug": "faridabad",
      "count": 2
    },
    {
      "canonical": "Ghaziabad",
      "slug": "ghaziabad",
      "count": 37
    },
    {
      "canonical": "Goa",
      "slug": "goa",
      "count": 1
    },
    {
      "canonical": "Guntur",
      "slug": "guntur",
      "count": 7
    },
    {
      "canonical": "Gurugram",
      "slug": "gurugram",
      "count": 111
    },
    {
      "canonical": "Guwahati",
      "slug": "guwahati",
      "count": 13
    },
    {
      "canonical": "Gwalior",
      "slug": "gwalior",
      "count": 2
    },
    {
      "canonical": "Hapur",
      "slug": "hapur",
      "count": 2
    },
    {
      "canonical": "Hosur",
      "slug": "hosur",
      "count": 22
    },
    {
      "canonical": "Hubli",
      "slug": "hubli",
      "count": 5
    },
    {
      "canonical": "Hyderabad",
      "slug": "hyderabad",
      "count": 123
    },
    {
      "canonical": "Indore",
      "slug": "indore",
      "count": 21
    },
    {
      "canonical": "Jabalpur",
      "slug": "jabalpur",
      "count": 1
    },
    {
      "canonical": "Jaipur",
      "slug": "jaipur",
      "count": 27
    },
    {
      "canonical": "Jalgaon",
      "slug": "jalgaon",
      "count": 1
    },
    {
      "canonical": "Jodhpur",
      "slug": "jodhpur",
      "count": 6
    },
    {
      "canonical": "Jorhat",
      "slug": "jorhat",
      "count": 2
    },
    {
      "canonical": "Kanpur",
      "slug": "kanpur",
      "count": 3
    },
    {
      "canonical": "Karnal",
      "slug": "karnal",
      "count": 3
    },
    {
      "canonical": "Kharagpur",
      "slug": "kharagpur",
      "count": 1
    },
    {
      "canonical": "Kheda",
      "slug": "kheda",
      "count": 1
    },
    {
      "canonical": "Kochi",
      "slug": "kochi",
      "count": 10
    },
    {
      "canonical": "Kolar",
      "slug": "kolar",
      "count": 9
    },
    {
      "canonical": "Kolhapur",
      "slug": "kolhapur",
      "count": 1
    },
    {
      "canonical": "Kolkata",
      "slug": "kolkata",
      "count": 43
    },
    {
      "canonical": "Kollam",
      "slug": "kollam",
      "count": 1
    },
    {
      "canonical": "Lucknow",
      "slug": "lucknow",
      "count": 49
    },
    {
      "canonical": "Ludhiana",
      "slug": "ludhiana",
      "count": 9
    },
    {
      "canonical": "Madurai",
      "slug": "madurai",
      "count": 5
    },
    {
      "canonical": "Manesar",
      "slug": "manesar",
      "count": 2
    },
    {
      "canonical": "Mangaluru",
      "slug": "mangaluru",
      "count": 12
    },
    {
      "canonical": "Medchal",
      "slug": "medchal",
      "count": 1
    },
    {
      "canonical": "Mohali",
      "slug": "mohali",
      "count": 6
    },
    {
      "canonical": "Mumbai",
      "slug": "mumbai",
      "count": 3
    },
    {
      "canonical": "Mundra",
      "slug": "mundra",
      "count": 3
    },
    {
      "canonical": "Mysore",
      "slug": "mysore",
      "count": 6
    },
    {
      "canonical": "Nagpur",
      "slug": "nagpur",
      "count": 15
    },
    {
      "canonical": "Narmadapuram",
      "slug": "narmadapuram",
      "count": 1
    },
    {
      "canonical": "Navi Mumbai",
      "slug": "navi-mumbai",
      "count": 24
    },
    {
      "canonical": "Nellore",
      "slug": "nellore",
      "count": 2
    },
    {
      "canonical": "Noida",
      "slug": "noida",
      "count": 18
    },
    {
      "canonical": "Palakkad",
      "slug": "palakkad",
      "count": 1
    },
    {
      "canonical": "Palwal",
      "slug": "palwal",
      "count": 4
    },
    {
      "canonical": "Patiala",
      "slug": "patiala",
      "count": 1
    },
    {
      "canonical": "Patna",
      "slug": "patna",
      "count": 27
    },
    {
      "canonical": "Perambalur",
      "slug": "perambalur",
      "count": 1
    },
    {
      "canonical": "Pune",
      "slug": "pune",
      "count": 36
    },
    {
      "canonical": "Raipur",
      "slug": "raipur",
      "count": 18
    },
    {
      "canonical": "Rajkot",
      "slug": "rajkot",
      "count": 11
    },
    {
      "canonical": "Rajpura",
      "slug": "rajpura",
      "count": 2
    },
    {
      "canonical": "Ranchi",
      "slug": "ranchi",
      "count": 7
    },
    {
      "canonical": "Rewari",
      "slug": "rewari",
      "count": 2
    },
    {
      "canonical": "Rohtak",
      "slug": "rohtak",
      "count": 1
    },
    {
      "canonical": "Rudrapur",
      "slug": "rudrapur",
      "count": 2
    },
    {
      "canonical": "Sagar",
      "slug": "sagar",
      "count": 1
    },
    {
      "canonical": "Salem",
      "slug": "salem",
      "count": 2
    },
    {
      "canonical": "Sanand",
      "slug": "sanand",
      "count": 1
    },
    {
      "canonical": "Satna",
      "slug": "satna",
      "count": 1
    },
    {
      "canonical": "Siliguri",
      "slug": "siliguri",
      "count": 1
    },
    {
      "canonical": "Solapur",
      "slug": "solapur",
      "count": 3
    },
    {
      "canonical": "Sonipat",
      "slug": "sonipat",
      "count": 7
    },
    {
      "canonical": "Surat",
      "slug": "surat",
      "count": 5
    },
    {
      "canonical": "Tepla",
      "slug": "tepla",
      "count": 4
    },
    {
      "canonical": "Tirupati",
      "slug": "tirupati",
      "count": 1
    },
    {
      "canonical": "Tiruppur",
      "slug": "tiruppur",
      "count": 1
    },
    {
      "canonical": "Tumakuru",
      "slug": "tumakuru",
      "count": 1
    },
    {
      "canonical": "Tumkur",
      "slug": "tumkur",
      "count": 2
    },
    {
      "canonical": "Vadodara",
      "slug": "vadodara",
      "count": 2
    },
    {
      "canonical": "Valsad",
      "slug": "valsad",
      "count": 3
    },
    {
      "canonical": "Varanasi",
      "slug": "varanasi",
      "count": 3
    },
    {
      "canonical": "Vijayawada",
      "slug": "vijayawada",
      "count": 17
    },
    {
      "canonical": "Visakhapatnam",
      "slug": "visakhapatnam",
      "count": 10
    }
  ],
  "RCC": [
    {
      "canonical": "Ahmedabad",
      "slug": "ahmedabad",
      "count": 7
    },
    {
      "canonical": "Aligarh",
      "slug": "aligarh",
      "count": 2
    },
    {
      "canonical": "Ambala",
      "slug": "ambala",
      "count": 1
    },
    {
      "canonical": "Anakapalli",
      "slug": "anakapalli",
      "count": 1
    },
    {
      "canonical": "Bengaluru",
      "slug": "bengaluru",
      "count": 176
    },
    {
      "canonical": "Bhiwandi",
      "slug": "bhiwandi",
      "count": 8
    },
    {
      "canonical": "Bhopal",
      "slug": "bhopal",
      "count": 1
    },
    {
      "canonical": "Bhubaneswar",
      "slug": "bhubaneswar",
      "count": 4
    },
    {
      "canonical": "Chandigarh",
      "slug": "chandigarh",
      "count": 4
    },
    {
      "canonical": "Chennai",
      "slug": "chennai",
      "count": 4
    },
    {
      "canonical": "Coimbatore",
      "slug": "coimbatore",
      "count": 3
    },
    {
      "canonical": "Delhi",
      "slug": "delhi",
      "count": 15
    },
    {
      "canonical": "Faridabad",
      "slug": "faridabad",
      "count": 1
    },
    {
      "canonical": "Ghaziabad",
      "slug": "ghaziabad",
      "count": 4
    },
    {
      "canonical": "Goa",
      "slug": "goa",
      "count": 1
    },
    {
      "canonical": "Guntur",
      "slug": "guntur",
      "count": 1
    },
    {
      "canonical": "Gurugram",
      "slug": "gurugram",
      "count": 17
    },
    {
      "canonical": "Hosur",
      "slug": "hosur",
      "count": 1
    },
    {
      "canonical": "Hubli",
      "slug": "hubli",
      "count": 2
    },
    {
      "canonical": "Hyderabad",
      "slug": "hyderabad",
      "count": 10
    },
    {
      "canonical": "Indore",
      "slug": "indore",
      "count": 8
    },
    {
      "canonical": "Jaipur",
      "slug": "jaipur",
      "count": 3
    },
    {
      "canonical": "Jalandhar",
      "slug": "jalandhar",
      "count": 1
    },
    {
      "canonical": "Kanpur",
      "slug": "kanpur",
      "count": 2
    },
    {
      "canonical": "Karnal",
      "slug": "karnal",
      "count": 2
    },
    {
      "canonical": "Kolar",
      "slug": "kolar",
      "count": 2
    },
    {
      "canonical": "Kolhapur",
      "slug": "kolhapur",
      "count": 2
    },
    {
      "canonical": "Kolkata",
      "slug": "kolkata",
      "count": 3
    },
    {
      "canonical": "Krishnagiri",
      "slug": "krishnagiri",
      "count": 1
    },
    {
      "canonical": "Kumta",
      "slug": "kumta",
      "count": 1
    },
    {
      "canonical": "Lucknow",
      "slug": "lucknow",
      "count": 22
    },
    {
      "canonical": "Madurai",
      "slug": "madurai",
      "count": 2
    },
    {
      "canonical": "Mangaluru",
      "slug": "mangaluru",
      "count": 3
    },
    {
      "canonical": "Mapusa",
      "slug": "mapusa",
      "count": 2
    },
    {
      "canonical": "Mumbai",
      "slug": "mumbai",
      "count": 6
    },
    {
      "canonical": "Mysore",
      "slug": "mysore",
      "count": 1
    },
    {
      "canonical": "Navi Mumbai",
      "slug": "navi-mumbai",
      "count": 4
    },
    {
      "canonical": "New Delhi",
      "slug": "new-delhi",
      "count": 1
    },
    {
      "canonical": "Noida",
      "slug": "noida",
      "count": 2
    },
    {
      "canonical": "North Goa",
      "slug": "north-goa",
      "count": 9
    },
    {
      "canonical": "Patna",
      "slug": "patna",
      "count": 4
    },
    {
      "canonical": "Puducherry",
      "slug": "puducherry",
      "count": 5
    },
    {
      "canonical": "Pune",
      "slug": "pune",
      "count": 1
    },
    {
      "canonical": "Raipur",
      "slug": "raipur",
      "count": 1
    },
    {
      "canonical": "Rajkot",
      "slug": "rajkot",
      "count": 13
    },
    {
      "canonical": "Shamli",
      "slug": "shamli",
      "count": 1
    },
    {
      "canonical": "Shivamogga",
      "slug": "shivamogga",
      "count": 2
    },
    {
      "canonical": "Surat",
      "slug": "surat",
      "count": 6
    },
    {
      "canonical": "Tirupati",
      "slug": "tirupati",
      "count": 2
    },
    {
      "canonical": "Vijayawada",
      "slug": "vijayawada",
      "count": 21
    },
    {
      "canonical": "Visakhapatnam",
      "slug": "visakhapatnam",
      "count": 2
    }
  ]
};

export const STATES_BY_TYPE: LocationsByType = {
  "PEB": [
    {
      "canonical": "Andhra Pradesh",
      "slug": "andhra-pradesh",
      "count": 40
    },
    {
      "canonical": "Assam",
      "slug": "assam",
      "count": 15
    },
    {
      "canonical": "Bihar",
      "slug": "bihar",
      "count": 27
    },
    {
      "canonical": "Chhattisgarh",
      "slug": "chhattisgarh",
      "count": 18
    },
    {
      "canonical": "Delhi",
      "slug": "delhi",
      "count": 23
    },
    {
      "canonical": "Goa",
      "slug": "goa",
      "count": 1
    },
    {
      "canonical": "Gujarat",
      "slug": "gujarat",
      "count": 69
    },
    {
      "canonical": "Haryana",
      "slug": "haryana",
      "count": 136
    },
    {
      "canonical": "Jharkhand",
      "slug": "jharkhand",
      "count": 7
    },
    {
      "canonical": "Karnataka",
      "slug": "karnataka",
      "count": 379
    },
    {
      "canonical": "Kerala",
      "slug": "kerala",
      "count": 20
    },
    {
      "canonical": "Madhya Pradesh",
      "slug": "madhya-pradesh",
      "count": 33
    },
    {
      "canonical": "Maharashtra",
      "slug": "maharashtra",
      "count": 134
    },
    {
      "canonical": "Odisha",
      "slug": "odisha",
      "count": 9
    },
    {
      "canonical": "Punjab",
      "slug": "punjab",
      "count": 22
    },
    {
      "canonical": "Rajasthan",
      "slug": "rajasthan",
      "count": 41
    },
    {
      "canonical": "Tamil Nadu",
      "slug": "tamil-nadu",
      "count": 91
    },
    {
      "canonical": "Telangana",
      "slug": "telangana",
      "count": 124
    },
    {
      "canonical": "Uttar Pradesh",
      "slug": "uttar-pradesh",
      "count": 123
    },
    {
      "canonical": "Uttarakhand",
      "slug": "uttarakhand",
      "count": 2
    },
    {
      "canonical": "West Bengal",
      "slug": "west-bengal",
      "count": 45
    }
  ],
  "RCC": [
    {
      "canonical": "Andhra Pradesh",
      "slug": "andhra-pradesh",
      "count": 27
    },
    {
      "canonical": "Bihar",
      "slug": "bihar",
      "count": 4
    },
    {
      "canonical": "Chandigarh",
      "slug": "chandigarh",
      "count": 4
    },
    {
      "canonical": "Chhattisgarh",
      "slug": "chhattisgarh",
      "count": 1
    },
    {
      "canonical": "Delhi",
      "slug": "delhi",
      "count": 16
    },
    {
      "canonical": "Goa",
      "slug": "goa",
      "count": 12
    },
    {
      "canonical": "Gujarat",
      "slug": "gujarat",
      "count": 26
    },
    {
      "canonical": "Haryana",
      "slug": "haryana",
      "count": 21
    },
    {
      "canonical": "Karnataka",
      "slug": "karnataka",
      "count": 187
    },
    {
      "canonical": "Madhya Pradesh",
      "slug": "madhya-pradesh",
      "count": 9
    },
    {
      "canonical": "Maharashtra",
      "slug": "maharashtra",
      "count": 21
    },
    {
      "canonical": "Odisha",
      "slug": "odisha",
      "count": 4
    },
    {
      "canonical": "Puducherry",
      "slug": "puducherry",
      "count": 5
    },
    {
      "canonical": "Punjab",
      "slug": "punjab",
      "count": 1
    },
    {
      "canonical": "Rajasthan",
      "slug": "rajasthan",
      "count": 3
    },
    {
      "canonical": "Tamil Nadu",
      "slug": "tamil-nadu",
      "count": 11
    },
    {
      "canonical": "Telangana",
      "slug": "telangana",
      "count": 10
    },
    {
      "canonical": "Uttar Pradesh",
      "slug": "uttar-pradesh",
      "count": 33
    },
    {
      "canonical": "West Bengal",
      "slug": "west-bengal",
      "count": 3
    }
  ]
};

// Only micromarkets past MICROMARKET_MIN_LISTINGS in scripts/lib/locations.mjs.
export const MICROMARKETS: MicromarketSummary[] = [
  {
    "canonical": "Aslali",
    "slug": "aslali",
    "count": 11,
    "parentCity": "Ahmedabad",
    "citySlug": "ahmedabad"
  },
  {
    "canonical": "Attibele",
    "slug": "attibele",
    "count": 14,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Bamnoli",
    "slug": "bamnoli",
    "count": 9,
    "parentCity": "Delhi",
    "citySlug": "delhi"
  },
  {
    "canonical": "Bannerghatta",
    "slug": "bannerghatta",
    "count": 12,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Begur",
    "slug": "begur",
    "count": 26,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Bharthal",
    "slug": "bharthal",
    "count": 9,
    "parentCity": "Delhi",
    "citySlug": "delhi"
  },
  {
    "canonical": "Bidadi",
    "slug": "bidadi",
    "count": 5,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Bidrahalli",
    "slug": "bidrahalli",
    "count": 38,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Bommanahalli",
    "slug": "bommanahalli",
    "count": 26,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Bommasandra",
    "slug": "bommasandra",
    "count": 18,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Budigere",
    "slug": "budigere",
    "count": 38,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Budihal",
    "slug": "budihal",
    "count": 21,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Chakan",
    "slug": "chakan",
    "count": 20,
    "parentCity": "Pune",
    "citySlug": "pune"
  },
  {
    "canonical": "Cheemasandra",
    "slug": "cheemasandra",
    "count": 38,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Chokkahalli",
    "slug": "chokkahalli",
    "count": 9,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Dadri",
    "slug": "dadri",
    "count": 6,
    "parentCity": "Dadri",
    "citySlug": "dadri"
  },
  {
    "canonical": "Dankuni",
    "slug": "dankuni",
    "count": 21,
    "parentCity": "Kolkata",
    "citySlug": "kolkata"
  },
  {
    "canonical": "Dasanapura",
    "slug": "dasanapura",
    "count": 13,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Devanahalli",
    "slug": "devanahalli",
    "count": 51,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Devaryamjal",
    "slug": "devaryamjal",
    "count": 27,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Dhulagori",
    "slug": "dhulagori",
    "count": 5,
    "parentCity": "Kolkata",
    "citySlug": "kolkata"
  },
  {
    "canonical": "Dobbaspet",
    "slug": "dobbaspet",
    "count": 34,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Ekarajapura",
    "slug": "ekarajapura",
    "count": 11,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Farukh Nagar",
    "slug": "farukh-nagar",
    "count": 9,
    "parentCity": "Gurugram",
    "citySlug": "gurugram"
  },
  {
    "canonical": "Harohalli",
    "slug": "harohalli",
    "count": 11,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Hoskote",
    "slug": "hoskote",
    "count": 76,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Hosur Road",
    "slug": "hosur-road",
    "count": 72,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "HSR",
    "slug": "hsr",
    "count": 26,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Jakkur",
    "slug": "jakkur",
    "count": 26,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Jigani",
    "slug": "jigani",
    "count": 27,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Kanakapura Road",
    "slug": "kanakapura-road",
    "count": 11,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Kelamangalam",
    "slug": "kelamangalam",
    "count": 9,
    "parentCity": "Hosur",
    "citySlug": "hosur"
  },
  {
    "canonical": "Kheda",
    "slug": "kheda",
    "count": 10,
    "parentCity": "Ahmedabad",
    "citySlug": "ahmedabad"
  },
  {
    "canonical": "Kherki Dhaula",
    "slug": "kherki-dhaula",
    "count": 7,
    "parentCity": "Gurugram",
    "citySlug": "gurugram"
  },
  {
    "canonical": "Kompally",
    "slug": "kompally",
    "count": 50,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Kudlu Gate",
    "slug": "kudlu-gate",
    "count": 26,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Kumbalgodu",
    "slug": "kumbalgodu",
    "count": 15,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Kuruli",
    "slug": "kuruli",
    "count": 7,
    "parentCity": "Pune",
    "citySlug": "pune"
  },
  {
    "canonical": "Makali",
    "slug": "makali",
    "count": 25,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Manesar",
    "slug": "manesar",
    "count": 11,
    "parentCity": "Gurugram",
    "citySlug": "gurugram"
  },
  {
    "canonical": "Marathalli",
    "slug": "marathalli",
    "count": 28,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Medchal",
    "slug": "medchal",
    "count": 13,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Narsapura",
    "slug": "narsapura",
    "count": 22,
    "parentCity": "Kolar",
    "citySlug": "kolar"
  },
  {
    "canonical": "Nelamangala",
    "slug": "nelamangala",
    "count": 104,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Noida",
    "slug": "noida",
    "count": 7,
    "parentCity": "Ghaziabad",
    "citySlug": "ghaziabad"
  },
  {
    "canonical": "Pataudi Road",
    "slug": "pataudi-road",
    "count": 12,
    "parentCity": "Gurugram",
    "citySlug": "gurugram"
  },
  {
    "canonical": "Peenya",
    "slug": "peenya",
    "count": 62,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Pirana",
    "slug": "pirana",
    "count": 6,
    "parentCity": "Ahmedabad",
    "citySlug": "ahmedabad"
  },
  {
    "canonical": "Rampura",
    "slug": "rampura",
    "count": 38,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Ranihati",
    "slug": "ranihati",
    "count": 6,
    "parentCity": "Kolkata",
    "citySlug": "kolkata"
  },
  {
    "canonical": "Sankrail",
    "slug": "sankrail",
    "count": 7,
    "parentCity": "Kolkata",
    "citySlug": "kolkata"
  },
  {
    "canonical": "Sarjapura",
    "slug": "sarjapura",
    "count": 28,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Shamshabad",
    "slug": "shamshabad",
    "count": 22,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Sidlaghatta Road",
    "slug": "sidlaghatta-road",
    "count": 11,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Sohna Road",
    "slug": "sohna-road",
    "count": 7,
    "parentCity": "Gurugram",
    "citySlug": "gurugram"
  },
  {
    "canonical": "Soukya Road",
    "slug": "soukya-road",
    "count": 16,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "T Begur",
    "slug": "t-begur",
    "count": 27,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Tauru Road",
    "slug": "tauru-road",
    "count": 10,
    "parentCity": "Gurugram",
    "citySlug": "gurugram"
  },
  {
    "canonical": "Uddanapalli",
    "slug": "uddanapalli",
    "count": 9,
    "parentCity": "Hosur",
    "citySlug": "hosur"
  },
  {
    "canonical": "Varthur",
    "slug": "varthur",
    "count": 28,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Vazhakkulam",
    "slug": "vazhakkulam",
    "count": 6,
    "parentCity": "Ernakulam",
    "citySlug": "ernakulam"
  },
  {
    "canonical": "Wagholi",
    "slug": "wagholi",
    "count": 10,
    "parentCity": "Pune",
    "citySlug": "pune"
  },
  {
    "canonical": "Whitefield",
    "slug": "whitefield",
    "count": 67,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Yelahanka",
    "slug": "yelahanka",
    "count": 26,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  }
];

// All named micromarkets for filters, including those without a standalone page.
// Counts and city membership use the backend's listing IDs; no tag parsing in the browser.
export const FILTER_MICROMARKETS: MicromarketSummary[] = [
  {
    "canonical": "Nelamangala",
    "slug": "nelamangala",
    "count": 103,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Hosur Road",
    "slug": "hosur-road",
    "count": 71,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Whitefield",
    "slug": "whitefield",
    "count": 67,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Hoskote",
    "slug": "hoskote",
    "count": 64,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Peenya",
    "slug": "peenya",
    "count": 62,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Devanahalli",
    "slug": "devanahalli",
    "count": 51,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Kompally",
    "slug": "kompally",
    "count": 47,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Bidrahalli",
    "slug": "bidrahalli",
    "count": 38,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Budigere",
    "slug": "budigere",
    "count": 38,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Cheemasandra",
    "slug": "cheemasandra",
    "count": 38,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Rampura",
    "slug": "rampura",
    "count": 38,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Dobbaspet",
    "slug": "dobbaspet",
    "count": 33,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Marathalli",
    "slug": "marathalli",
    "count": 28,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Sarjapura",
    "slug": "sarjapura",
    "count": 28,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Varthur",
    "slug": "varthur",
    "count": 28,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Jigani",
    "slug": "jigani",
    "count": 27,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "T Begur",
    "slug": "t-begur",
    "count": 27,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Begur",
    "slug": "begur",
    "count": 26,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Bommanahalli",
    "slug": "bommanahalli",
    "count": 26,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "HSR",
    "slug": "hsr",
    "count": 26,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Jakkur",
    "slug": "jakkur",
    "count": 26,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Kudlu Gate",
    "slug": "kudlu-gate",
    "count": 26,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Yelahanka",
    "slug": "yelahanka",
    "count": 26,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Makali",
    "slug": "makali",
    "count": 25,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Devaryamjal",
    "slug": "devaryamjal",
    "count": 24,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Shamshabad",
    "slug": "shamshabad",
    "count": 22,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Budihal",
    "slug": "budihal",
    "count": 21,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Dankuni",
    "slug": "dankuni",
    "count": 21,
    "parentCity": "Kolkata",
    "citySlug": "kolkata"
  },
  {
    "canonical": "Chakan",
    "slug": "chakan",
    "count": 20,
    "parentCity": "Pune",
    "citySlug": "pune"
  },
  {
    "canonical": "Bommasandra",
    "slug": "bommasandra",
    "count": 18,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Soukya Road",
    "slug": "soukya-road",
    "count": 16,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Kumbalgodu",
    "slug": "kumbalgodu",
    "count": 15,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Attibele",
    "slug": "attibele",
    "count": 13,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Dasanapura",
    "slug": "dasanapura",
    "count": 13,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Medchal",
    "slug": "medchal",
    "count": 13,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Bannerghatta",
    "slug": "bannerghatta",
    "count": 12,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Hoskote",
    "slug": "hoskote",
    "count": 12,
    "parentCity": "Kolar",
    "citySlug": "kolar"
  },
  {
    "canonical": "Narsapura",
    "slug": "narsapura",
    "count": 12,
    "parentCity": "Kolar",
    "citySlug": "kolar"
  },
  {
    "canonical": "Pataudi Road",
    "slug": "pataudi-road",
    "count": 12,
    "parentCity": "Gurugram",
    "citySlug": "gurugram"
  },
  {
    "canonical": "Aslali",
    "slug": "aslali",
    "count": 11,
    "parentCity": "Ahmedabad",
    "citySlug": "ahmedabad"
  },
  {
    "canonical": "Ekarajapura",
    "slug": "ekarajapura",
    "count": 11,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Harohalli",
    "slug": "harohalli",
    "count": 11,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Kanakapura Road",
    "slug": "kanakapura-road",
    "count": 11,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Sidlaghatta Road",
    "slug": "sidlaghatta-road",
    "count": 11,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Narsapura",
    "slug": "narsapura",
    "count": 10,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Wagholi",
    "slug": "wagholi",
    "count": 10,
    "parentCity": "Pune",
    "citySlug": "pune"
  },
  {
    "canonical": "Bamnoli",
    "slug": "bamnoli",
    "count": 9,
    "parentCity": "Delhi",
    "citySlug": "delhi"
  },
  {
    "canonical": "Bharthal",
    "slug": "bharthal",
    "count": 9,
    "parentCity": "Delhi",
    "citySlug": "delhi"
  },
  {
    "canonical": "Chokkahalli",
    "slug": "chokkahalli",
    "count": 9,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Farukh Nagar",
    "slug": "farukh-nagar",
    "count": 9,
    "parentCity": "Gurugram",
    "citySlug": "gurugram"
  },
  {
    "canonical": "Kheda",
    "slug": "kheda",
    "count": 9,
    "parentCity": "Ahmedabad",
    "citySlug": "ahmedabad"
  },
  {
    "canonical": "Manesar",
    "slug": "manesar",
    "count": 9,
    "parentCity": "Gurugram",
    "citySlug": "gurugram"
  },
  {
    "canonical": "Kelamangalam",
    "slug": "kelamangalam",
    "count": 8,
    "parentCity": "Hosur",
    "citySlug": "hosur"
  },
  {
    "canonical": "Tauru Road",
    "slug": "tauru-road",
    "count": 8,
    "parentCity": "Gurugram",
    "citySlug": "gurugram"
  },
  {
    "canonical": "Uddanapalli",
    "slug": "uddanapalli",
    "count": 8,
    "parentCity": "Hosur",
    "citySlug": "hosur"
  },
  {
    "canonical": "Kuruli",
    "slug": "kuruli",
    "count": 7,
    "parentCity": "Pune",
    "citySlug": "pune"
  },
  {
    "canonical": "Sankrail",
    "slug": "sankrail",
    "count": 7,
    "parentCity": "Kolkata",
    "citySlug": "kolkata"
  },
  {
    "canonical": "Sohna Road",
    "slug": "sohna-road",
    "count": 7,
    "parentCity": "Gurugram",
    "citySlug": "gurugram"
  },
  {
    "canonical": "Kherki Dhaula",
    "slug": "kherki-dhaula",
    "count": 6,
    "parentCity": "Gurugram",
    "citySlug": "gurugram"
  },
  {
    "canonical": "Pirana",
    "slug": "pirana",
    "count": 6,
    "parentCity": "Ahmedabad",
    "citySlug": "ahmedabad"
  },
  {
    "canonical": "Ranihati",
    "slug": "ranihati",
    "count": 6,
    "parentCity": "Kolkata",
    "citySlug": "kolkata"
  },
  {
    "canonical": "Bidadi",
    "slug": "bidadi",
    "count": 5,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Dhulagori",
    "slug": "dhulagori",
    "count": 5,
    "parentCity": "Kolkata",
    "citySlug": "kolkata"
  },
  {
    "canonical": "Alipur",
    "slug": "alipur",
    "count": 4,
    "parentCity": "Delhi",
    "citySlug": "delhi"
  },
  {
    "canonical": "Budhpur",
    "slug": "budhpur",
    "count": 4,
    "parentCity": "Delhi",
    "citySlug": "delhi"
  },
  {
    "canonical": "Dwarka Expressway",
    "slug": "dwarka-expressway",
    "count": 4,
    "parentCity": "Delhi",
    "citySlug": "delhi"
  },
  {
    "canonical": "Gundlapochampally",
    "slug": "gundlapochampally",
    "count": 4,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Noida",
    "slug": "noida",
    "count": 4,
    "parentCity": "Ghaziabad",
    "citySlug": "ghaziabad"
  },
  {
    "canonical": "Sanathal",
    "slug": "sanathal",
    "count": 4,
    "parentCity": "Ahmedabad",
    "citySlug": "ahmedabad"
  },
  {
    "canonical": "Sarkhej",
    "slug": "sarkhej",
    "count": 4,
    "parentCity": "Ahmedabad",
    "citySlug": "ahmedabad"
  },
  {
    "canonical": "South Delhi",
    "slug": "south-delhi",
    "count": 4,
    "parentCity": "Delhi",
    "citySlug": "delhi"
  },
  {
    "canonical": "Transport Nagar",
    "slug": "transport-nagar",
    "count": 4,
    "parentCity": "Lucknow",
    "citySlug": "lucknow"
  },
  {
    "canonical": "Changodar",
    "slug": "changodar",
    "count": 3,
    "parentCity": "Ahmedabad",
    "citySlug": "ahmedabad"
  },
  {
    "canonical": "Dadri",
    "slug": "dadri",
    "count": 3,
    "parentCity": "Dadri",
    "citySlug": "dadri"
  },
  {
    "canonical": "Kallakal",
    "slug": "kallakal",
    "count": 3,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Mundka",
    "slug": "mundka",
    "count": 3,
    "parentCity": "Delhi",
    "citySlug": "delhi"
  },
  {
    "canonical": "Thally Road",
    "slug": "thally-road",
    "count": 3,
    "parentCity": "Hosur",
    "citySlug": "hosur"
  },
  {
    "canonical": "Vazhakkulam",
    "slug": "vazhakkulam",
    "count": 3,
    "parentCity": "Ernakulam",
    "citySlug": "ernakulam"
  },
  {
    "canonical": "Vazhakkulam",
    "slug": "vazhakkulam",
    "count": 3,
    "parentCity": "Kochi",
    "citySlug": "kochi"
  },
  {
    "canonical": "Angamaly",
    "slug": "angamaly",
    "count": 2,
    "parentCity": "Ernakulam",
    "citySlug": "ernakulam"
  },
  {
    "canonical": "Azadpur Mandi",
    "slug": "azadpur-mandi",
    "count": 2,
    "parentCity": "Delhi",
    "citySlug": "delhi"
  },
  {
    "canonical": "Banda Mailaram",
    "slug": "banda-mailaram",
    "count": 2,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Bijwasan",
    "slug": "bijwasan",
    "count": 2,
    "parentCity": "Delhi",
    "citySlug": "delhi"
  },
  {
    "canonical": "Dadri",
    "slug": "dadri",
    "count": 2,
    "parentCity": "Noida",
    "citySlug": "noida"
  },
  {
    "canonical": "Devaryamjal",
    "slug": "devaryamjal",
    "count": 2,
    "parentCity": "Bhiwandi",
    "citySlug": "bhiwandi"
  },
  {
    "canonical": "Gaganpahad",
    "slug": "gaganpahad",
    "count": 2,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Jeedipalle",
    "slug": "jeedipalle",
    "count": 2,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Kistapur",
    "slug": "kistapur",
    "count": 2,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Kompally",
    "slug": "kompally",
    "count": 2,
    "parentCity": "Bhiwandi",
    "citySlug": "bhiwandi"
  },
  {
    "canonical": "Maheshtala",
    "slug": "maheshtala",
    "count": 2,
    "parentCity": "Kolkata",
    "citySlug": "kolkata"
  },
  {
    "canonical": "Nadarganj",
    "slug": "nadarganj",
    "count": 2,
    "parentCity": "Lucknow",
    "citySlug": "lucknow"
  },
  {
    "canonical": "Sathamrai",
    "slug": "sathamrai",
    "count": 2,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Taratala",
    "slug": "taratala",
    "count": 2,
    "parentCity": "Kolkata",
    "citySlug": "kolkata"
  },
  {
    "canonical": "Tauru Road",
    "slug": "tauru-road",
    "count": 2,
    "parentCity": "Bilaspur",
    "citySlug": "bilaspur"
  },
  {
    "canonical": "Attibele",
    "slug": "attibele",
    "count": 1,
    "parentCity": "Hosur",
    "citySlug": "hosur"
  },
  {
    "canonical": "Autonagar",
    "slug": "autonagar",
    "count": 1,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Bijwasan",
    "slug": "bijwasan",
    "count": 1,
    "parentCity": "Gurugram",
    "citySlug": "gurugram"
  },
  {
    "canonical": "Changodar",
    "slug": "changodar",
    "count": 1,
    "parentCity": "Sanand",
    "citySlug": "sanand"
  },
  {
    "canonical": "Dadri",
    "slug": "dadri",
    "count": 1,
    "parentCity": "Ghaziabad",
    "citySlug": "ghaziabad"
  },
  {
    "canonical": "Devaryamjal",
    "slug": "devaryamjal",
    "count": 1,
    "parentCity": "Jaipur",
    "citySlug": "jaipur"
  },
  {
    "canonical": "Dobbaspet",
    "slug": "dobbaspet",
    "count": 1,
    "parentCity": "Tumkur",
    "citySlug": "tumkur"
  },
  {
    "canonical": "Ghevra",
    "slug": "ghevra",
    "count": 1,
    "parentCity": "Delhi",
    "citySlug": "delhi"
  },
  {
    "canonical": "Greater Noida",
    "slug": "greater-noida",
    "count": 1,
    "parentCity": "Noida",
    "citySlug": "noida"
  },
  {
    "canonical": "Hosur Road",
    "slug": "hosur-road",
    "count": 1,
    "parentCity": "Hosur",
    "citySlug": "hosur"
  },
  {
    "canonical": "Kelamangalam",
    "slug": "kelamangalam",
    "count": 1,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Kheda",
    "slug": "kheda",
    "count": 1,
    "parentCity": "Kheda",
    "citySlug": "kheda"
  },
  {
    "canonical": "Kherki Dhaula",
    "slug": "kherki-dhaula",
    "count": 1,
    "parentCity": "Manesar",
    "citySlug": "manesar"
  },
  {
    "canonical": "Kompally",
    "slug": "kompally",
    "count": 1,
    "parentCity": "Jaipur",
    "citySlug": "jaipur"
  },
  {
    "canonical": "Kothur",
    "slug": "kothur",
    "count": 1,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Manesar",
    "slug": "manesar",
    "count": 1,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Manesar",
    "slug": "manesar",
    "count": 1,
    "parentCity": "Manesar",
    "citySlug": "manesar"
  },
  {
    "canonical": "Nelamangala",
    "slug": "nelamangala",
    "count": 1,
    "parentCity": "Tumkur",
    "citySlug": "tumkur"
  },
  {
    "canonical": "Noida",
    "slug": "noida",
    "count": 1,
    "parentCity": "Indore",
    "citySlug": "indore"
  },
  {
    "canonical": "Noida",
    "slug": "noida",
    "count": 1,
    "parentCity": "Jaipur",
    "citySlug": "jaipur"
  },
  {
    "canonical": "Noida",
    "slug": "noida",
    "count": 1,
    "parentCity": "Noida",
    "citySlug": "noida"
  },
  {
    "canonical": "North Paravur",
    "slug": "north-paravur",
    "count": 1,
    "parentCity": "Kochi",
    "citySlug": "kochi"
  },
  {
    "canonical": "Patancheru",
    "slug": "patancheru",
    "count": 1,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Sidlaghatta Road/Ekarajapura",
    "slug": "sidlaghatta-road-ekarajapura",
    "count": 1,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Tukkuguda",
    "slug": "tukkuguda",
    "count": 1,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  },
  {
    "canonical": "Uddanapalli",
    "slug": "uddanapalli",
    "count": 1,
    "parentCity": "Bengaluru",
    "citySlug": "bengaluru"
  },
  {
    "canonical": "Yellampet",
    "slug": "yellampet",
    "count": 1,
    "parentCity": "Hyderabad",
    "citySlug": "hyderabad"
  }
];

// Ranked at build time by fresh API listing counts, highest first.
// Ties use the canonical name, then the full location ID.
export const POPULAR_LOCATION_IDS: Record<'states' | 'cities' | 'micromarkets', string[]> = {
  "states": [
    "states/karnataka",
    "states/maharashtra",
    "states/uttar-pradesh",
    "states/haryana",
    "states/tamil-nadu",
    "states/telangana"
  ],
  "cities": [
    "cities/bengaluru",
    "cities/hyderabad",
    "cities/gurugram",
    "cities/lucknow",
    "cities/ahmedabad",
    "cities/bhiwandi"
  ],
  "micromarkets": [
    "micromarkets/bengaluru/nelamangala",
    "micromarkets/bengaluru/hoskote",
    "micromarkets/bengaluru/hosur-road",
    "micromarkets/bengaluru/whitefield",
    "micromarkets/bengaluru/peenya"
  ]
};
