// AUTO-GENERATED by scripts/generate-micromarkets.mjs — do not edit by hand.
// Published CMS content matched to eligible, canonical backend geography.
import type { NavigationGuide } from '@/lib/locationNavigation';

export const navigationGuide: NavigationGuide | null = {
  "label": "Kompally",
  "parentLabel": "Hyderabad",
  "href": "/overview/telangana/hyderabad/kompally",
  "image": {
    "url": "https://pub-94c0eb3cd2df4e71a1b6f5b73273bc71.r2.dev/blogs/whatsapp-image-2026-05-21-at-11-22-30-1e79b9a8d025fb1f.webp",
    "alt": "Warehouse in Kompally, Hyderabad",
    "width": 1600,
    "height": 1200
  }
};
